//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintForm.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComplaintForm.Domain.Resources.LayoutUI", typeof(LayoutUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact OPC&apos;s Information Centre.
        /// </summary>
        public static string ContactOPCsInfoCenterText {
            get {
                return ResourceManager.GetString("ContactOPCsInfoCenterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.priv.gc.ca/en/contact-the-opc/contact-the-information-centre/.
        /// </summary>
        public static string ContactOPCsInfoCenterURL {
            get {
                return ResourceManager.GetString("ContactOPCsInfoCenterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request. Please try again later or contact us with the contact information at the &lt;a href=&quot;https://www.priv.gc.ca/en/contact-the-opc/contact-the-information-centre/&quot; target=&quot;_blank&quot;&gt;information center&lt;/a&gt; with the following error id: &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string ErrorContent {
            get {
                return ResourceManager.GetString("ErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a formal privacy complaint.
        /// </summary>
        public static string FileFormalPrivacyComplaintText {
            get {
                return ResourceManager.GetString("FileFormalPrivacyComplaintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.priv.gc.ca/en/report-a-concern/file-a-formal-privacy-complaint/.
        /// </summary>
        public static string FileFormalPrivacyComplaintURL {
            get {
                return ResourceManager.GetString("FileFormalPrivacyComplaintURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a privacy complaint against a federal institution.
        /// </summary>
        public static string FilePAText {
            get {
                return ResourceManager.GetString("FilePAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.priv.gc.ca/en/report-a-concern/file-a-formal-privacy-complaint/file-a-complaint-about-a-federal-institution/.
        /// </summary>
        public static string FilePAURL {
            get {
                return ResourceManager.GetString("FilePAURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a complaint about a business.
        /// </summary>
        public static string FilePIPEDAText {
            get {
                return ResourceManager.GetString("FilePIPEDAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.priv.gc.ca/en/report-a-concern/file-a-formal-privacy-complaint/file-a-complaint-about-a-business/.
        /// </summary>
        public static string FilePIPEDAURL {
            get {
                return ResourceManager.GetString("FilePIPEDAURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.priv.gc.ca/en/.
        /// </summary>
        public static string HomeURL {
            get {
                return ResourceManager.GetString("HomeURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link provided is available for a single use only or you have surpassed the maxium session time of 2 hours. Please re-register with one of the links below to submit a new complaint..
        /// </summary>
        public static string InvalidRegistrationText {
            get {
                return ResourceManager.GetString("InvalidRegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Registration / Session Timeout.
        /// </summary>
        public static string InvalidRegistrationTitle {
            get {
                return ResourceManager.GetString("InvalidRegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selection.
        /// </summary>
        public static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Help?.
        /// </summary>
        public static string NeedHelp {
            get {
                return ResourceManager.GetString("NeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you are looking for has not been found. Please use your browser to return back or create a new complaint with us under the following links:.
        /// </summary>
        public static string NotFoundText {
            get {
                return ResourceManager.GetString("NotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office of the Privacy Commissioner of Canada.
        /// </summary>
        public static string OPCLong {
            get {
                return ResourceManager.GetString("OPCLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a concern.
        /// </summary>
        public static string ReportConcernText {
            get {
                return ResourceManager.GetString("ReportConcernText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.priv.gc.ca/en/report-a-concern/.
        /// </summary>
        public static string ReportConcernURL {
            get {
                return ResourceManager.GetString("ReportConcernURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here:.
        /// </summary>
        public static string YouAreHere {
            get {
                return ResourceManager.GetString("YouAreHere", resourceCulture);
            }
        }
    }
}
