//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintForm.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Registration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComplaintForm.Domain.Resources.Registration", typeof(Registration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add information to a pre-existing case.
        /// </summary>
        public static string AddInfoToPreExistingCase {
            get {
                return ResourceManager.GetString("AddInfoToPreExistingCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///  The person who made the complaint and the organization or institution the complaint is against may add extra information or documents about the complaint with the Office of the Privacy Commissioner of Canada (OPC).
        ///&lt;/p&gt;
        ///
        ///&lt;p&gt;
        ///  First, please submit your email address below. We will email you a unique link to access the form to add information or documents.
        ///&lt;/p&gt;.
        /// </summary>
        public static string ComplainantsOrRespondentsMayAddExtraInfoOrDocs {
            get {
                return ResourceManager.GetString("ComplainantsOrRespondentsMayAddExtraInfoOrDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This message has been automatically generated as the first step 
        ///    of submitting documents or information relating to an existing privacy complaint already submitted to the Office of the Privacy Commissioner of Canada.
        ///&lt;/p&gt;
        ///&lt;p&gt;To continue, please use this &lt;a href=&quot;{0}&quot;&gt;unique link to the document drop-off.&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;b&gt;Important information&lt;/b&gt;&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;For security reasons, you may only use the unique link once&lt;/li&gt;
        ///    &lt;li&gt;If you haven’t entered anything for two hours, the session wil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailDropOff {
            get {
                return ResourceManager.GetString("EmailDropOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This message has been automatically generated as the first step 
        ///    of making a privacy complaint to the Office of the Privacy Commissioner of Canada.
        ///&lt;/p&gt;
        ///&lt;p&gt;To continue, please &lt;a href=&quot;{0}&quot;&gt;fill out our online complaint form using this unique link.&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;b&gt;Important information&lt;/b&gt;&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li&gt;For security reasons, you may only use the unique link once&lt;/li&gt;
        ///    &lt;li&gt;If you haven’t entered anything for two hours, the session will end and your information will be deleted&lt;/li&gt;
        ///    &lt;li&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailPaAndPipeda {
            get {
                return ResourceManager.GetString("EmailPaAndPipeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting documents.
        /// </summary>
        public static string EmailTitleDropOff {
            get {
                return ResourceManager.GetString("EmailTitleDropOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a privacy complaint.
        /// </summary>
        public static string EmailTitlePaAndPipeda {
            get {
                return ResourceManager.GetString("EmailTitlePaAndPipeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a complaint about a federal institution.
        /// </summary>
        public static string FileAPaComplaintText {
            get {
                return ResourceManager.GetString("FileAPaComplaintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a complaint about a business.
        /// </summary>
        public static string FileAPipedaComplaintText {
            get {
                return ResourceManager.GetString("FileAPipedaComplaintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a PA Complaint.
        /// </summary>
        public static string FilePAComplaint {
            get {
                return ResourceManager.GetString("FilePAComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a PIPEDA Complaint.
        /// </summary>
        public static string FilePIPEDAComplaint {
            get {
                return ResourceManager.GetString("FilePIPEDAComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not receive the email within a few minutes, please &lt;a href=&quot;https://www.priv.gc.ca/en/contact-the-opc/contact-the-information-centre/&quot;&gt;contact OPC’s Information Centre.&lt;/a&gt;.
        /// </summary>
        public static string IfYouDoNotReceiveEmailContactOPC {
            get {
                return ResourceManager.GetString("IfYouDoNotReceiveEmailContactOPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Complaint Form.
        /// </summary>
        public static string OnlineComplaintForm {
            get {
                return ResourceManager.GetString("OnlineComplaintForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA Complaint.
        /// </summary>
        public static string PAComplaint {
            get {
                return ResourceManager.GetString("PAComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIPEDA Complaint.
        /// </summary>
        public static string PIPEDAComplaint {
            get {
                return ResourceManager.GetString("PIPEDAComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, please submit your email address below. We will email you a unique link to complete your complaint online..
        /// </summary>
        public static string PleaseSubmitEmailFirst {
            get {
                return ResourceManager.GetString("PleaseSubmitEmailFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration—Document drop-off.
        /// </summary>
        public static string RegistrationAddInfoOnComplaint {
            get {
                return ResourceManager.GetString("RegistrationAddInfoOnComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access our online privacy complaint form (private sector organization).
        /// </summary>
        public static string RegistrationOnlineBusiness {
            get {
                return ResourceManager.GetString("RegistrationOnlineBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access our Online privacy complaint form (federal institution).
        /// </summary>
        public static string RegistrationOnlineFederal {
            get {
                return ResourceManager.GetString("RegistrationOnlineFederal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for submitting your email address. You will receive an email from
        ///            &lt;a href=&quot;mailto:NePasRepondre-DoNotRepl%20hrefy@priv.gc.ca&quot;&gt;NePasRepondre-DoNotReply@priv.gc.ca&lt;/a&gt; with a link to complete your complaint online.
        ///            If you use a security filter, make sure to set it to allow messages from this email address..
        /// </summary>
        public static string ThanksForSubmittingOnlineComplaint {
            get {
                return ResourceManager.GetString("ThanksForSubmittingOnlineComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive an email with a unique link to add information
        ///            &lt;a href=&quot;mailto:NePasRepondre-DoNotRepl%20hrefy@priv.gc.ca&quot;&gt;NePasRepondre-DoNotReply@priv.gc.ca&lt;/a&gt; with a link to complete your complaint online.
        ///            If you use a security filter, make sure to set it to allow messages from this email address..
        /// </summary>
        public static string ThanksForSubmittingOnlineComplaintSuppInfo {
            get {
                return ResourceManager.GetString("ThanksForSubmittingOnlineComplaintSuppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You!.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site requires JavaScript. You might have difficulties doing certain actions. Please consider turning it on..
        /// </summary>
        public static string ThisSiteRequiresJavascript {
            get {
                return ResourceManager.GetString("ThisSiteRequiresJavascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use your browser navigation to go back to the previous page..
        /// </summary>
        public static string UseBrowserForNavigation {
            get {
                return ResourceManager.GetString("UseBrowserForNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this form for the same privacy complaint against another public sector institution..
        /// </summary>
        public static string UseFormAgainstAnotherFederalInstitution {
            get {
                return ResourceManager.GetString("UseFormAgainstAnotherFederalInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this form for additional privacy complaints against the same federal government institution..
        /// </summary>
        public static string UseFormAgainstSameFederalInstitution {
            get {
                return ResourceManager.GetString("UseFormAgainstSameFederalInstitution", resourceCulture);
            }
        }
    }
}
