//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintForm.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComplaintForm.Domain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountant.
        /// </summary>
        public static string Accountant {
            get {
                return ResourceManager.GetString("Accountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline.
        /// </summary>
        public static string Airline {
            get {
                return ResourceManager.GetString("Airline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        public static string Alberta {
            get {
                return ResourceManager.GetString("Alberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because &quot;Both&quot; is selected, at least one file has to be uploaded..
        /// </summary>
        public static string AtLeastOneFileHasToBeUploaded {
            get {
                return ResourceManager.GetString("AtLeastOneFileHasToBeUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one item must be selected..
        /// </summary>
        public static string AtLeastOneItemMustBeSelected {
            get {
                return ResourceManager.GetString("AtLeastOneItemMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Columbia.
        /// </summary>
        public static string British_Columbia {
            get {
                return ResourceManager.GetString("British_Columbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field should only contain digits.
        /// </summary>
        public static string CanOnlyContainDigits {
            get {
                return ResourceManager.GetString("CanOnlyContainDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check all that apply.
        /// </summary>
        public static string CheckAllThatApply {
            get {
                return ResourceManager.GetString("CheckAllThatApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Agency.
        /// </summary>
        public static string Collection_Agency {
            get {
                return ResourceManager.GetString("Collection_Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against a collection agency&lt;/h2&gt;
        ///&lt;p&gt;Collection agencies are subject to consumer protection regulations enforced by consumer affairs offices, as well as being subject to the &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA).&lt;/p&gt;
        ///&lt;p&gt;Consumer affairs offices enforce rules about collection agencies’ conduct, such as how and when they can contact people, and how much proof of the debt they need to show. Your provincial or territorial consumer affairs office may be bet [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Collection_Agency_Answer {
            get {
                return ResourceManager.GetString("Collection_Agency_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your complaint relate to the handling of personal information outside your province of residence?.
        /// </summary>
        public static string ComplaintAboutHandlingOfInformation {
            get {
                return ResourceManager.GetString("ComplaintAboutHandlingOfInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your complaint about being &lt;strong&gt;denied access&lt;/strong&gt; to your &lt;strong&gt;personal information&lt;/strong&gt;?.
        /// </summary>
        public static string ComplaintAgainstAccess {
            get {
                return ResourceManager.GetString("ComplaintAgainstAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your complaint is against any of the following types of organizations, please check all that apply..
        /// </summary>
        public static string ComplaintAgainstAnyOfFollowing {
            get {
                return ResourceManager.GetString("ComplaintAgainstAnyOfFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your complaint against any of these types of organizations?.
        /// </summary>
        public static string ComplaintAgainstFollowingOrganizations {
            get {
                return ResourceManager.GetString("ComplaintAgainstFollowingOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is that complaint process still ongoing?.
        /// </summary>
        public static string ComplaintStillOngoing {
            get {
                return ResourceManager.GetString("ComplaintStillOngoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you filed a complaint about your concerns with another body (other than the organization your complaint is against)?.
        /// </summary>
        public static string ComplaintToOtherBody {
            get {
                return ResourceManager.GetString("ComplaintToOtherBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Reporting Agency (for example, Equifax or Transunion).
        /// </summary>
        public static string Credit_Reporting_Agency {
            get {
                return ResourceManager.GetString("Credit_Reporting_Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Union.
        /// </summary>
        public static string Credit_Union {
            get {
                return ResourceManager.GetString("Credit_Union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If yes, please describe what accommodation measures you are requesting and the reason. If you are unable to do so in writing,
        ///please &lt;a href=&quot;https://www.priv.gc.ca/en/contact-the-opc/contact-the-information-centre/&quot;&gt;Contact OPC’s Information Centre&lt;/a&gt; for assistance..
        /// </summary>
        public static string DisabilityAccommodation {
            get {
                return ResourceManager.GetString("DisabilityAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you submitting the complaint as a customer or as an employee of the organization?.
        /// </summary>
        public static string EmployeeOrCustomer {
            get {
                return ResourceManager.GetString("EmployeeOrCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is over the {0} characters limit..
        /// </summary>
        public static string FieldIsOverCharacterLimit {
            get {
                return ResourceManager.GetString("FieldIsOverCharacterLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you filing this complaint &lt;strong&gt;on your own behalf&lt;/strong&gt; (or for a minor child you are guardian of) or &lt;strong&gt;on behalf of someone else&lt;/strong&gt;?.
        /// </summary>
        public static string FilingComplaintOnOwnBehalf {
            get {
                return ResourceManager.GetString("FilingComplaintOnOwnBehalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your complaint about the handling of personal information by a health practitioner (e.g. a doctor, nurse, pharmacist, chiropractor, psychologist, etc.) or a health clinic or hospital?.
        /// </summary>
        public static string HandlingOfHealthPractioner {
            get {
                return ResourceManager.GetString("HandlingOfHealthPractioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your complaint about the handling of personal information by any of the following:.
        /// </summary>
        public static string HandlingofPersonalInfoHealth {
            get {
                return ResourceManager.GetString("HandlingofPersonalInfoHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///                        &lt;li&gt;a provincial ministry, agency, board, commission or police force&lt;/li&gt;
        ///                        &lt;li&gt;a publically funded school, university or college&lt;/li&gt;
        ///                        &lt;li&gt;a local government institution such as a municipality, local police, library, school board, or transit  commissions&lt;/li&gt;
        ///                    &lt;/ul&gt;.
        /// </summary>
        public static string HandlingofPersonalInfoHealthList {
            get {
                return ResourceManager.GetString("HandlingofPersonalInfoHealthList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you submitted a complaint in the past with the Office of the Privacy Commissioner (OPC)?.
        /// </summary>
        public static string HaveYouSubmittedBefore {
            get {
                return ResourceManager.GetString("HaveYouSubmittedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have no supporting documents to provide.
        /// </summary>
        public static string IHaveNoSupportingDocuments {
            get {
                return ResourceManager.GetString("IHaveNoSupportingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your complaint about the handling of personal information during or in relation to an independent medical exam conducted for an employer or insurance company (for example to determine fitness to work or eligibility for benefits)?.
        /// </summary>
        public static string IndependantPhysicalExam {
            get {
                return ResourceManager.GetString("IndependantPhysicalExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Please put the complainant&apos;s information in the Complainant section below, and your information as their representative in the Representative section below.&lt;/p&gt;.
        /// </summary>
        public static string InstructionsTextRepresentative {
            get {
                return ResourceManager.GetString("InstructionsTextRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Instructions&lt;/h2&gt;.
        /// </summary>
        public static string InstructionsTextTitle {
            get {
                return ResourceManager.GetString("InstructionsTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance company.
        /// </summary>
        public static string Insurance_Company {
            get {
                return ResourceManager.GetString("Insurance_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against an insurance company&lt;/h2&gt;
        ///&lt;p&gt;Insurance companies must follow insurance laws and regulations, as well as following the &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA). Most insurance companies are required to be members of an independent dispute resolution service.&lt;/p&gt;
        ///&lt;p&gt;Two independent complaint resolution bodies, overseen by the Canadian Council of Insurance Regulators, address consumer complaints.&lt;/p&gt;
        ///&lt;ul&gt;
        ///  &lt;li&gt;For car and auto insurance complaint [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Insurance_Company_Answer {
            get {
                return ResourceManager.GetString("Insurance_Company_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your complaint against any of the following types of organizations?.
        /// </summary>
        public static string IsAgainstFwub {
            get {
                return ResourceManager.GetString("IsAgainstFwub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord or co-op housing.
        /// </summary>
        public static string LandlordOrCoopHousing {
            get {
                return ResourceManager.GetString("LandlordOrCoopHousing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against a landlord&lt;/h2&gt;
        ///&lt;p&gt;Landlords must follow provincial and territorial tenancy regulations, enforced by their residential tenancies regulatory body, as well as following the &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA). These bodies can address a wide range of landlord-tenant issues, including the handling of personal information and privacy.&lt;/p&gt;
        ///&lt;p&gt;Your provincial or territorial regulatory body may be better able to address your concerns, if your issue [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LandlordOrCoopHousing_Answer {
            get {
                return ResourceManager.GetString("LandlordOrCoopHousing_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer.
        /// </summary>
        public static string Lawyer {
            get {
                return ResourceManager.GetString("Lawyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against a lawyer&lt;/h2&gt;
        ///&lt;p&gt;Lawyers must follow professional conduct standards, set by their provincial or territorial law society, as well as following the &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA).&lt;/p&gt;
        ///&lt;p&gt;Law societies oversee rules of professional conduct, including privacy issues. A law society may be better able to address your concerns if your issue goes beyond privacy.&lt;/p&gt;
        ///&lt;h2&gt;What you can do&lt;/h2&gt;
        ///&lt;p&gt;Before filing a complaint with us, you may:&lt;/p&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Lawyer_Answer {
            get {
                return ResourceManager.GetString("Lawyer_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///                        &lt;li&gt;Airport or port&lt;/li&gt;
        ///                        &lt;li&gt;Bank&lt;/li&gt;
        ///                        &lt;li&gt;First nation band council&lt;/li&gt;
        ///                        &lt;li&gt;Interprovincial or international transportation company (freight or passenger, by land, water or air)&lt;/li&gt;
        ///                        &lt;li&gt;Off-shore drilling operation or organization involved in nuclear-related activity&lt;/li&gt;
        ///                        &lt;li&gt;Phone company, Internet service provider (ISP), or telecommunications infrast [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ListOfOrganizationFwubPipeda {
            get {
                return ResourceManager.GetString("ListOfOrganizationFwubPipeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///                            &lt;li&gt;Airport or port&lt;/li&gt;
        ///                            &lt;li&gt;Bank&lt;/li&gt;
        ///                            &lt;li&gt;First nations band council&lt;/li&gt;
        ///                            &lt;li&gt;Interprovincial or international transportation company (freight or passenger, by land, water or air)&lt;/li&gt;
        ///                            &lt;li&gt;Offshore-drilling operation, or organization involved in nuclear-related activity&lt;/li&gt;
        ///                            &lt;li&gt;Phone company, an Internet service provider (ISP), o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ListOfOrganizationPipeda {
            get {
                return ResourceManager.GetString("ListOfOrganizationPipeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manitoba.
        /// </summary>
        public static string Manitoba {
            get {
                return ResourceManager.GetString("Manitoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept these terms before submitting your complaint..
        /// </summary>
        public static string MustAcceptTerms {
            get {
                return ResourceManager.GetString("MustAcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against your employer&lt;/h2&gt;
        ///&lt;p&gt;Generally, under the &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA), people must try to resolve their privacy concerns with an organization before making a privacy complaint. We strongly encourage any unionized employees to first go through the grievance process.&lt;/p&gt;
        ///&lt;p&gt;If your privacy concern is related to larger issues of illegal discrimination, workplace safety, wage issues, or wrongful firing, there may be other ways to more f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string My_Employer_Answer {
            get {
                return ResourceManager.GetString("My_Employer_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inappropriate collection of personal information.
        /// </summary>
        public static string NatureOfComplaintCollection {
            get {
                return ResourceManager.GetString("NatureOfComplaintCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information has been collected that is not required for an operating program or activity of the institution; personal information is not collected directly from the individual concerned; or the individual is not advised of the purpose of the collection of personal information..
        /// </summary>
        public static string NatureOfComplaintCollectionInformation {
            get {
                return ResourceManager.GetString("NatureOfComplaintCollectionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack of correction of personal information (notation).
        /// </summary>
        public static string NatureOfComplaintCorrection {
            get {
                return ResourceManager.GetString("NatureOfComplaintCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The institution has not corrected the information or placed a notation on the file showing the requested correction..
        /// </summary>
        public static string NatureOfComplaintCorrectionInformation {
            get {
                return ResourceManager.GetString("NatureOfComplaintCorrectionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed response to your request.
        /// </summary>
        public static string NatureOfComplaintDelay {
            get {
                return ResourceManager.GetString("NatureOfComplaintDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The institution has not responded to your access or correction request within the statutory time limits. Under the &lt;i&gt;Privacy Act&lt;/i&gt; institutions have thirty (30) days after your request is received to respond (or 60 days if an extension has been properly invoked for an access request)..
        /// </summary>
        public static string NatureOfComplaintDelayInformation {
            get {
                return ResourceManager.GetString("NatureOfComplaintDelayInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denial of access to personal information.
        /// </summary>
        public static string NatureOfComplaintDenialOfAccess {
            get {
                return ResourceManager.GetString("NatureOfComplaintDenialOfAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information has not been received, either because some documents or information are missing or the institution has applied exemptions to withhold information..
        /// </summary>
        public static string NatureOfComplaintDenialOfAccessInformation {
            get {
                return ResourceManager.GetString("NatureOfComplaintDenialOfAccessInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objecting to institutions’ request for an extension to respond (to your access request).
        /// </summary>
        public static string NatureOfComplaintExtensionOfTime {
            get {
                return ResourceManager.GetString("NatureOfComplaintExtensionOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institutions may seek, with a reason set out in the Act, an extension of a further thirty (30) days to respond..
        /// </summary>
        public static string NatureOfComplaintExtensionOfTimeInformation {
            get {
                return ResourceManager.GetString("NatureOfComplaintExtensionOfTimeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response to formal request for access to personal information not provided in the official language or alternative format requested.
        /// </summary>
        public static string NatureOfComplaintLanguage {
            get {
                return ResourceManager.GetString("NatureOfComplaintLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string NatureOfComplaintOther {
            get {
                return ResourceManager.GetString("NatureOfComplaintOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrongful retention or disposal of personal information.
        /// </summary>
        public static string NatureOfComplaintRetentionAndDisposal {
            get {
                return ResourceManager.GetString("NatureOfComplaintRetentionAndDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information has not been kept in accordance with retention and disposal schedules (approved by National Archives); either destroyed too soon or kept too long. Personal information used for an administrative purpose must be kept for at least two years after the last administrative action unless the individual consents to its disposal..
        /// </summary>
        public static string NatureOfComplaintRetentionAndDisposalInformation {
            get {
                return ResourceManager.GetString("NatureOfComplaintRetentionAndDisposalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrongful use or disclosure of personal information.
        /// </summary>
        public static string NatureOfComplaintUseAndDisclosure {
            get {
                return ResourceManager.GetString("NatureOfComplaintUseAndDisclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal information has been used or disclosed without the consent of the individual and does not meet one of the permissible uses or disclosures without consent set out in &lt;a href=&quot;http://laws.justice.gc.ca/eng/acts/P-21/page-2.html#h-6&quot;&gt;sections 7 and 8 of the &lt;i&gt;Privacy Act&lt;/i&gt;&lt;/a&gt;..
        /// </summary>
        public static string NatureOfComplaintUseAndDisclosureInformation {
            get {
                return ResourceManager.GetString("NatureOfComplaintUseAndDisclosureInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are committed to ensuring that clients with disabilities have equal access to,
        ///and can benefit from, all our public-facing services. Will you need accommodation measures for the complaint investigation process?.
        /// </summary>
        public static string NeedsDisabilityAccommodation {
            get {
                return ResourceManager.GetString("NeedsDisabilityAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brunswick.
        /// </summary>
        public static string New_Brunswick {
            get {
                return ResourceManager.GetString("New_Brunswick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newfoundland And Labrador.
        /// </summary>
        public static string Newfoundland_And_Labrador {
            get {
                return ResourceManager.GetString("Newfoundland_And_Labrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northwest Territories.
        /// </summary>
        public static string Northwest_Territories {
            get {
                return ResourceManager.GetString("Northwest_Territories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Scotia.
        /// </summary>
        public static string Nova_Scotia {
            get {
                return ResourceManager.GetString("Nova_Scotia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nunavut.
        /// </summary>
        public static string Nunavut {
            get {
                return ResourceManager.GetString("Nunavut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario.
        /// </summary>
        public static string Ontario {
            get {
                return ResourceManager.GetString("Ontario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An organization for calling you even though you are on the national &quot;Do Not Call list&quot;.
        /// </summary>
        public static string OrganizationCallOnDoNotCallList {
            get {
                return ResourceManager.GetString("OrganizationCallOnDoNotCallList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint about telemarketing or unwanted calls, despite being on the &quot;Do not call list&quot;&lt;/h2&gt;
        ///&lt;h2&gt;What you can do&lt;/h2&gt;
        ///&lt;p&gt;Before filing a complaint with us, you may:&lt;/p&gt;
        ///&lt;ul&gt;
        ///  &lt;li&gt;&lt;a href=&quot;https://lnnte-dncl.gc.ca/en#forConsumers&quot;&gt;make a complaint to the Canada’s national “Do not call list”&lt;/a&gt;&lt;/li&gt;
        ///  &lt;li&gt;raise your concerns in writing with the phone company or Internet service provider&apos;s designated contact for privacy (otherwise, we may not investigate): &lt;a href=&quot;https://www.priv.gc.ca/en/privacy [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrganizationCallOnDoNotCallList_Answer {
            get {
                return ResourceManager.GetString("OrganizationCallOnDoNotCallList_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An organization for sending you an unsolicited marketing email (Spam) without a working &apos;unsubscribe&apos; link.
        /// </summary>
        public static string OrganizationSentUnsolicitedEmail {
            get {
                return ResourceManager.GetString("OrganizationSentUnsolicitedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint about unsolicited marketing emails or texts (spam) without a link to unsubscribe&lt;/h2&gt;
        ///&lt;h2&gt;What you can do&lt;/h2&gt;
        ///&lt;p&gt;If your complaint is against an organization &lt;strong&gt;you don’t have an ongoing relationship with&lt;/strong&gt;, you can: &lt;a href=&quot;http://fightspam.gc.ca/eic/site/030.nsf/frm-eng/MMCN-9EZV6S&quot;&gt;make your complaint to the National Spam Reporting Centre&lt;/a&gt;. The centre gathers information to help enforce Canada&apos;s Anti-Spam Legislation (CASL).&lt;/p&gt;
        ///&lt;p&gt;If your complaint is against an organiz [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrganizationSentUnsolicitedEmail_Answer {
            get {
                return ResourceManager.GetString("OrganizationSentUnsolicitedEmail_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other (Outside of Canada).
        /// </summary>
        public static string Other_NotUS {
            get {
                return ResourceManager.GetString("Other_NotUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone or Internet Service Provider.
        /// </summary>
        public static string Phone_Or_Internet_Service_Provider {
            get {
                return ResourceManager.GetString("Phone_Or_Internet_Service_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against a phone or Internet service provider&lt;/h2&gt;
        ///&lt;p&gt;Phone and Internet service providers must follow rules set by the Canadian Radio-television and Telecommunications Commission (CRTC), as well as following the &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA). People may make complaints about Canadian telecommunications and television services to the Commission for Complaints for Telecom-television Services (CCTS).&lt;/p&gt;
        ///&lt;p&gt;The commission handles a wide range of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Phone_Or_Internet_Service_Provider_Answer {
            get {
                return ResourceManager.GetString("Phone_Or_Internet_Service_Provider_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number..
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid postal code..
        /// </summary>
        public static string PostalCodeInvalid {
            get {
                return ResourceManager.GetString("PostalCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrefixProvinces {
            get {
                return ResourceManager.GetString("PrefixProvinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrefixProvinces_De {
            get {
                return ResourceManager.GetString("PrefixProvinces_De", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrefixProvinces_De_l {
            get {
                return ResourceManager.GetString("PrefixProvinces_De_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrefixProvinces_De_la {
            get {
                return ResourceManager.GetString("PrefixProvinces_De_la", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrefixProvinces_Du {
            get {
                return ResourceManager.GetString("PrefixProvinces_Du", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PrefixQuebec {
            get {
                return ResourceManager.GetString("PrefixQuebec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prince Edward Island.
        /// </summary>
        public static string Prince_Edward_Island {
            get {
                return ResourceManager.GetString("Prince_Edward_Island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What province or territory did the incident or practice you are concerned about occur in?.
        /// </summary>
        public static string ProvinceOrTerritoryIncident {
            get {
                return ResourceManager.GetString("ProvinceOrTerritoryIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did the {0} Privacy Commissioner specifically refer you to the Office of the Privacy Commissioner of Canada?.
        /// </summary>
        public static string ProvincePcReferedToCanadaPc {
            get {
                return ResourceManager.GetString("ProvincePcReferedToCanadaPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quebec.
        /// </summary>
        public static string Quebec {
            get {
                return ResourceManager.GetString("Quebec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta Information and Privacy Commissioner’s Office.
        /// </summary>
        public static string Question1_Alberta_PC {
            get {
                return ResourceManager.GetString("Question1_Alberta_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC Information and Privacy Commissioner’s Office.
        /// </summary>
        public static string Question1_BC_PC {
            get {
                return ResourceManager.GetString("Question1_BC_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information and Privacy Commissioner’s Office.
        /// </summary>
        public static string Question1_Information_PC {
            get {
                return ResourceManager.GetString("Question1_Information_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission d&apos;accès à l&apos;information du Québec.
        /// </summary>
        public static string Question1_QC_PC {
            get {
                return ResourceManager.GetString("Question1_QC_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity or not-for-profit (other than credit-union, co-op housing, or daycare).
        /// </summary>
        public static string Question3_A {
            get {
                return ResourceManager.GetString("Question3_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against a charity or not-for-profit organization&lt;/h2&gt;
        ///&lt;p&gt;The &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA) applies to the collection, use and disclosure of personal information during a &lt;a href=&quot;https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/pipeda-compliance-help/pipeda-interpretation-bulletins/interpretations_03_ca/&quot;&gt;commercial activity&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;The core activities o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Question3_A_Answer {
            get {
                return ResourceManager.GetString("Question3_A_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condominium corporation.
        /// </summary>
        public static string Question3_B {
            get {
                return ResourceManager.GetString("Question3_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against a condominium (condo) corporation or its agent&lt;/h2&gt;
        ///&lt;p&gt;The &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA) applies to the collection, use and disclosure of personal information during a &lt;a href=&quot;https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/pipeda-compliance-help/pipeda-interpretation-bulletins/interpretations_03_ca/&quot;&gt;commercial activity&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Usually, PIPEDA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Question3_B_Answer {
            get {
                return ResourceManager.GetString("Question3_B_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federal government institution.
        /// </summary>
        public static string Question3_C {
            get {
                return ResourceManager.GetString("Question3_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against a federal government institution&lt;/h2&gt;
        ///&lt;p&gt;Federal government institutions are covered by the federal &lt;em&gt;Privacy Act&lt;/em&gt;, not by the Personal Information Protection and Electronic Documents Act (PIPEDA).&lt;/p&gt; 
        ///&lt;h2&gt;What you can do&lt;/h2&gt;
        ///&lt;a href=&quot;https://www.priv.gc.ca/en/report-a-concern/file-a-formal-privacy-complaint/file-a-complaint-about-a-federal-institution/&quot;&gt;File a privacy complaint about a federal institution&lt;/a&gt;.
        /// </summary>
        public static string Question3_C_Answer {
            get {
                return ResourceManager.GetString("Question3_C_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Nation band council.
        /// </summary>
        public static string Question3_D {
            get {
                return ResourceManager.GetString("Question3_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against a First Nation band council&lt;/h2&gt;
        ///&lt;p&gt;The &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA) applies only if the complaint is about the handling of personal information:&lt;/p&gt;
        ///&lt;ul&gt;
        ///  &lt;li&gt;about an employee of a First Nation band council, or&lt;/li&gt;
        ///  &lt;li&gt;during a &lt;a href=&quot;https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/pipeda-compliance-help/pipeda-interpretation-bulletins/in [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Question3_D_Answer {
            get {
                return ResourceManager.GetString("Question3_D_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string Question3_E {
            get {
                return ResourceManager.GetString("Question3_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against an individual&lt;/h2&gt;
        ///&lt;p&gt;The &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA) applies to the collection, use and disclosure of personal information by an organization during a &lt;a href=&quot;https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/pipeda-compliance-help/pipeda-interpretation-bulletins/interpretations_03_ca/&quot;&gt;commercial activity&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Therefore, PIPEDA only applie [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Question3_E_Answer {
            get {
                return ResourceManager.GetString("Question3_E_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization engaged in journalism (online or offline newspaper, magazine, radio or TV broadcaster).
        /// </summary>
        public static string Question3_F {
            get {
                return ResourceManager.GetString("Question3_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against an online or offline newspaper, magazine, radio, or TV broadcaster&lt;/h2&gt;
        ///&lt;p&gt;The &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA) does not apply to any information that is collected, used, or disclosed only for journalistic, artistic or literary purposes.&lt;/p&gt;
        ///&lt;p&gt;In this context, PIPEDA usually doesn&apos;t cover anything collected, used or disclosed in articles or broadcasts.&lt;/p&gt;
        ///&lt;p&gt;However, PIPEDA does cover the handling of subscribers’ personal information.&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Question3_F_Answer {
            get {
                return ResourceManager.GetString("Question3_F_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Political party.
        /// </summary>
        public static string Question3_G {
            get {
                return ResourceManager.GetString("Question3_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against a political party&lt;/h2&gt;
        ///&lt;p&gt;The &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA) applies to the collection, use and disclosure of personal information during a &lt;a href=&quot;https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/the-personal-information-protection-and-electronic-documents-act-pipeda/pipeda-compliance-help/pipeda-interpretation-bulletins/interpretations_03_ca/&quot;&gt;commercial activity&lt;/a&gt;.
        ///&lt;p&gt;The core activities of political parties &lt;strong [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Question3_G_Answer {
            get {
                return ResourceManager.GetString("Question3_G_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you raised your concern in writing with the organization’s contact for privacy issues (often called the privacy officer)?.
        /// </summary>
        public static string RaisedConcernToPrivacyOfficer {
            get {
                return ResourceManager.GetString("RaisedConcernToPrivacyOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you raised your privacy concerns in writing with the institution&apos;s &lt;a href=&quot;http://www.tbs-sct.gc.ca/ap/atip-aiprp/coord-eng.asp&quot;&gt;Access to Information and Privacy (ATIP) Coordinator&lt;/a&gt;?.
        /// </summary>
        public static string RaisedPrivacyToAtipCoordinator {
            get {
                return ResourceManager.GetString("RaisedPrivacyToAtipCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtor.
        /// </summary>
        public static string Realtor {
            get {
                return ResourceManager.GetString("Realtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Complaint against a realtor&lt;/h2&gt;
        ///&lt;p&gt;Realtors must follow provincial and territorial real estate regulations, enforced by real estate regulatory bodies, as well as following the &lt;em&gt;Personal Information Protection and Electronic Documents Act&lt;/em&gt; (PIPEDA).&lt;/p&gt;
        ///&lt;p&gt;Real estate regulatory bodies oversee professional conduct, and may therefore be better able to address your concerns if your issue goes beyond privacy.&lt;/p&gt;
        ///&lt;h2&gt;What you can do&lt;/h2&gt;
        ///&lt;p&gt;Before filing a complaint with us, you may:&lt;/p&gt;
        ///&lt;ul&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Realtor_Answer {
            get {
                return ResourceManager.GetString("Realtor_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saskatchewan.
        /// </summary>
        public static string Saskatchewan {
            get {
                return ResourceManager.GetString("Saskatchewan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send them by mail.
        /// </summary>
        public static string SendByMail {
            get {
                return ResourceManager.GetString("SendByMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Agent.
        /// </summary>
        public static string Travel_Agent {
            get {
                return ResourceManager.GetString("Travel_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United-States.
        /// </summary>
        public static string UnitedStates {
            get {
                return ResourceManager.GetString("UnitedStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload them.
        /// </summary>
        public static string UploadThem {
            get {
                return ResourceManager.GetString("UploadThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which &lt;strong&gt;federal government institution&lt;/strong&gt; is your complaint against?.
        /// </summary>
        public static string WhichFederalGovernementInstitutionComplaintAgainst {
            get {
                return ResourceManager.GetString("WhichFederalGovernementInstitutionComplaintAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of the following choices most accurately summarizes your complaint?.
        /// </summary>
        public static string WhichOneOfTheseChoicesSummarizesYourComplaint {
            get {
                return ResourceManager.GetString("WhichOneOfTheseChoicesSummarizesYourComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Employer.
        /// </summary>
        public static string Your_Employer {
            get {
                return ResourceManager.GetString("Your_Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yukon.
        /// </summary>
        public static string Yukon {
            get {
                return ResourceManager.GetString("Yukon", resourceCulture);
            }
        }
    }
}
