export const piaTestData = {
    HasLegalAuthority: true,
    RelevantLegislationPolicies:
        "SUVVCQNXCEECGALJWEHVFQUMMYOYYVIRGPJEAHWWIDTQEPWGRGKDSWXCYIICCNYGUMUPQGIPHJM PVOFBEKFNQAYGWJOQSBMAFNHFDOEJNRRYFNSTMMUIROKVHBHMJUNXPGJHHYWOGUAYIABIPUEGGD JCGQRGTQYJCMQGGRGQELVTUIHYMKXGMURWMNGKAGSTNUDFXPLGWKEHROHWISTJRRVGTTTSKVQXR",
    ProgramName: "UULJPJTHVCRIFTPONJLXAPUXV",
    IsNewprogram: true,
    ProgamHasMajorChanges: true,
    IsProgamContractedOut: true,
    IsProgramInvolvePersonalInformation: true,
    ContactATIPQ16: "no_email",
    UserEmailAddress16: "THPUIIKCUL@gmail.com",
    PersonalInfoUsedFor: "admin_purpose",
    ContactATIPQ18: "receive_email",
    UserEmailAddress18: "AHRLQKAWFS@gmail.com",
    SubjectOfPIA: "program_activity",
    ContactATIPQ110: "no_email",
    UserEmailAddress110: "RHKRNFDMLM@gmail.com",
    SingleOrMultiInstitutionPIA: "single",
    RelatedPIANameInstitution: "YMHSAIQOYTDYLYSODUQUCJWPS",
    RelatedPIANameProgram: "FNYYPGNBPAMAOEKIMPJHTKBEU",
    RelatedPIADescription: "FWPKWKKLVYUKHXHHTINSOGPBL",
    BehalfSingleInstitution: "1",
    BehalfSingleInstitutionOther: "SUUGGMJDHWIIVRWQQCCTLJMMW",
    BehalfMultipleInstitutionLead: "",
    BehalfMultipleInstitutionLeadOther: "EXOGBVHAGNDEABBRJRUAQJHTX",
    HasLeadInstitutionConsultedOther: "yes",
    LeadInstitutionHasNotConsultedOtherReason:
        "XJIOPAMHGHIHHDAULKNFGFKRJIUVUIIWAQNXNGWNVVVOEKTKVJGANAQSYQFHFQLXYLHPPCGEMAI KJYJNYMKECSGKFXVGDGASESKNFCMXDBXQRHMUBOWUQAETRBIHWCVWWRGQOVHWALBATORXLBENJE RPRPKKFXUMFGXSITHYGLUQRCRIBXCCJFSOSRRKIORGKSUHTIAIKCEYRBWPWCIGVRDAMIYQBVQQS",
    IsTreasuryBoardApproval: true,
    HeadYourInstitutionFullname: "DQLLWLEHUDQAPVWDIVYHADJJQ",
    HeadYourInstitutionTitle: "XGHUGVJDQFVVSQUJAPQWSKVEP",
    HeadYourInstitutionSection: "FTXSLDSAUWCICWHVQBPCEQBHA",
    HeadYourInstitutionEmail: "EXTYIJTGST@gmail.com",
    SeniorOfficialFullname: "PPKIUTKELYKRAVBNQAANJDEYG",
    SeniorOfficialTitle: "HUEUQVYGKLAYPRVPVYUEIRIKI",
    SeniorOfficialSection: "OGYQWKHOGUDXNQEQQINDODJNG",
    SeniorOfficialEmail: "YVCITWBISS@gmail.com",
    PersonContact: "PPKIUTKELYKRAVBNQAANJDEYG",
    AnotherContactFullname: "GJUITGEGSWISQHTIVCLXCUPJG",
    AnotherContactTitle: "LKYHWUCNUODWACJMYAKLUBHXW",
    AnotherContactSection: "BQDTERYQFKFQARSKOQOKSCWON",
    AnotherContactEmail: "MLPFUQLADS@gmail.com",
    NewOrUpdatedPIA: "update_pia",
    UpdatePIANumberAssigned: "update_pia_existing_reference_number",
    UpdatePIAAllReferenceNumbersAssigned: "YCAEAHEERPCAUFGFVNQNHASQR",
    DetailsPreviousSubmission:
        "WNRCDVTURMUCVUBCSPSLXQJFDXQFOTSXQTHWUHAGKOQHJGCQNYXWLSVFELXFENFXSWKBMEGKOMA FCHMCPAYYPEUQVFFRCXPEOYCVEVTDDFRNQPSRAKOEQHAKTESBTPGRXWQCFPXSFUUJLGAGMMQQIL JDUJGNUTXVNFFUPWJOTASYGTFMLGCVUOAHIHWMSJGMRQWBGMEGDXDQAJWADSCOQBBXEWMHAVVJS",
    NewPIANumberAssigned: "new_pia_existing_reference_number",
    NewPIAAllReferenceNumbersAssigned: "LVEQLFFCSIMWDYXXISAGVUTCE",
    ProgramOverview:
        "IAREMDFCMQAPJYIBYASKNAQMIQNUIVPQQWBFELEEUYGLPNJHEILBWTKIJEVVOKSPAIYLWDWNVOP JDUXFEAJBIXLVVJLKAVVPAOLFHLILWTEUBSCJARAGCXWDRDJXRBKRECJOJSWSQXENSPUDGBKHUO QSJNMEPUYDXLRTUWAHWGOMBAAKGTQYJCGHGUBCYIDDSSEUFHQILMNMODRINCXVDASVEJMYVXHNC",
    ParticipationOptions: "participation_mandatory_and_automatic",
    OtherInitiatives: true,
    OtherInitiativesDescription:
        "CVGTRLRVLSRKWFCDGJOFLPDXLHQXVNMPXUKLVPJWNXKTEVHQWORFQRVLRHIKUTAXGCMBTPHPAQR XVWTDXRWFCAVQUQDLVNWVUNCBKEWXFSJSNGXNEULOARRJVGPLBXYMMOCITRSTTYYIPCDOROHBCI PBFTHYHAEGYLJDRJOAQESEPPQEEKFGABLIJDSTCNEFXOBLKHGRDTNVYLKOCDTVTWFWYBSNPTXCA",
    DurationOptions: "one_time",
    DurationOptionsDescriptions:
        "CPNEOKCTRNXNERFCGJAPKCRJOPMGKKMVBNCGXQMISNFRVGEHWTXVHYNAWDPXXVIGABLPOYEOWQV VWDKGFGPKQXMOYPKWJUIQKGRCKUCAEPVAUTYFAOXFSTOWNDDCWVKOCNLQKIUJEOFBCLSFQFVTWD FUGMSCKKSURDBBMAFBFSRWDIAIUAYOLEACLVYRXILCBOIUYNCJBIKMKIQWLKHJLDINDXOPANDWH",
    IsProgramRolledOutPhases: true,
    IsAnticipatedStartDate: true,
    AnticipatedStartDate:
        "IQAMMMLFWARSMELAXYSMMDPTXASXFFELNAPLAJWDIIWOVLDOPBYTTVVEAFOMTMARUFELNYANBOE FVLMUKNICPGWLKJSTUYTPCBBQENCKUVDALOYSNFJQGHJEPDRJVTHGTRDUJUPVKXHSCVAVJAFPPC TAWUVUFLHXFIYSCPLESSGVCKMELSKUEWUAGGIFWHEPMEGCLIVDJTEJKXXLHRJMALTIMXMVHFHLO",
    IsAnticipatedEndDate: true,
    AnticipatedEndDate:
        "EYWHJGEJRUQLHMLLFVSMUYDXGCXBXEEPPCBDMLNWSINLKYMYAADIKDCFVXBGHCKMPBVFKHXSIVS DQSJQYIXHKNCNBLICBEVXFXEIHWHLPIGBLMULEBMVFCHCXGHVGSFCOTWRNAIBAMRCGBCNQWXARA HVIEJUYSAMVLSIISSHNDQUSQOXNDVPRVRUXKDOHADWYGKAUQNYCIYRBMDQPKGUWKTATXKWPEAMY",
    IsInvolveNewSoftware: true,
    InvolveNewSoftwareDescription:
        "NJTWLEGFPUMWKDEKXUQDNIALIPJJPJHFLUPWKIMKGMPGEPQHGJURTCSFIHNUUWPGNHLOMHAPHFW WMYBSCXJHSFASEKCDJXWBJNHLLCIWIASJBPCJLWINTSQSEUCVAPTHEENXROHAOLYSLQROHSQMOI GKGFURAXLDRRSHWKENSFMYGHUTXLDKCXCHJALJDUDDQMRWBQMATRFXLGEYJASOUBBSPLXWXUKXB",
    DoesRequireModificationToIT: true,
    RequireModificationToITDescription:
        "HISLSYADIPPBXPISFPTWTVWLJRRSVSHRYOMOGQEQIXEEHIJICOPJVTPLKHCBHGGOIXBICSLNLCO THJQCCVYKHFIJQYTCMKBRDBAKOFNGVACUKJUCVKHOBFIVLYAFHCRULOQFIFMVHROGDMYGERFCCL EHJGLAVYQCPACIXLIKMIQQYUWKURWKLVFBOLMFHPKQOJPVNTIBYOLHMNINJBEECFQSTBSMYCCWW",
    HaschangesToBusinessRequirements: true,
    ChangesToBusinessRequirements:
        "XRLJAKJSRJIVSKCIAAWOFHKJYJDXHKEJTFGKJIGDUWIGAIIOILITRWWQHBJPHLKGEYCMERYQTTT ILAMNBBHEIJEXGWOPMVIEVFRKFKBBROQFOMHKYFEVRDBOAGSVEITTWFMFICIQYGLSRYJSODPGQM KVVKMLAWXTXEFLCILHWRFSLFIAHXXNWFSKHIKARXUYUMWVOHWQTAXXVQKQCLEBYJVRLUETWLPXV",
    WillITLegacySystemRetained: true,
    AwarenessActivities:
        "UQQVVJHSHRGSHXTURRLMGBXNWAMRFGXWFLIWBKTQAKJTPVHPKDBWTATTSDXUVPMASIMUOWSHXUM YOEFRDMMVJKPSLNPQPKHDHJCXUSMDIXDELGCNRYIMLSEMUJYMGSHKOUQFCHVKYIMLHLGELBXPBU XPITCRDSDQYWCEADTUONCCVLLXEPKRUWILRSAVVTQRUGLPEPVIGWXESVSWIENNHLVCNQLHCWXTV",
    ScopeThisPhase:
        "OBWSIFMSOQURPIUPTMAQIODHLTJHOHNEMWNKNISTJJGPDUEKIWSIHCDAXOGNUEEHCPFRTJCLSGG QRBIEUEMGEGUYQUNNPORHQHRTXDPXAWEWLHAWIRILJJGQSKFCQSRQDOAJINGQOOFHBWNJTPEWFF LCCOOUHHKFMCHAYFUIVEYMWPPXVAEHUOHDJAHQLOPFAVQNDLNMYIQLLYFLYQXHCCKWUEPXWDVHN",
    ScopeOtherPhases:
        "DFBNRRYIPMNUFHYHHNHFPSKXXSVCKACFYFFSTQIAGWWUCGBOYWDGABCJUCPYVWXPKHUABFMQEHX QHOGHIESKBNUWSYYTJXAREXHBJFIHGAPACKOCWJFFCVBVRGRCFNXNYDMIGEXCVLEAWTUHKVWARU CJUYDUWHHDMCEFYSEYEICMAQBELUGIXAJRHGOJMJJYGNDNRMYFISWRLPIDWXJBAXFMRMWSEULUX",
    NotInScopePia:
        "MJKBWUBISBAAJLMSTVTTGYUXEUADBPCTDBAAXTWUIQJODEBVUCLECGLNNLWBUWGDXFWILMTYXYK AIRUXFQTQIFVQJYMVILYYSUEHHFRWVDJYCAKUWQITVXHRBCYGCNDSESGNMMQAXVUEUWOJNRXQDF ROWHPYXXMYNLJTQCYMNFBOUYKWGUAJRBHQNYAMDIVNHSKMNKBEWOXSUDTWWSSCXCHLESFRBMJFI",
    ScopePia:
        "UXHTULYVGHVMGQXJBQAMQWBISQAWRQDPBPHUHTPWPTFETBIVIEBBSWEWVXADLCDODFLPJCCGADW KOHCVKPSGDSIAMJKADCYIEPWVEWRORUHMJDYNXNEXWHRAFHTJDESIPUFXJFQNXDOIKUQIJVCOXA KOSPNLOQGMIXVADGEYVHKJSUKVDLRKGMSDTJGEKHSFBTNNUOVSCFCBKAVWFRHDXUGVFRGSAYONN",
    NotInScope:
        "RJBROUVXIEYVDRWDKWNMLVAAELUKDXIAWVLRQYKCGOLYKNHTBMKJTBXVJANCYLTKUYYGGEMKLLF PAISKAVABMCKWNWMNUHTLSHVUFBPXWSCPWXLKOGQYNHAGINQWITABOKVRLWEYGCDSATYPKBXNPU DHLMRPTCHMRRSTDYVSIWGGJRVJSDKQFXTIAOTJVNRSFNNQJMAVTUFHJVXTQIVQRQHSXJTNELVTF",
    WhyProgramNecessary:
        "XKLJJGPOABSFOMWMPYVAWYDPOARAOEPSQHGJKWXWOTEKYXOPFCXIFFBXHVTIOOAVKAOHGMCSAYK LUWUVTLVHQVKDYGKNRNFBTGUHJQTXDUPFRJGUJVCUYJTDXXVKOXOYSARNBNMDQWEVGELPAOEULK YKXGFTUCAJHRAYKPMCOQNWQQFFJJXRPJPTTMCDGRQRXAGUNFVTXCBGABTHBAKKEHSWCGFXMJUWA",
    DoesMeasureEffectiveness: true,
    HowMeasureEffectiveness:
        "UKGFSGWFIQGVMGUFRWUFFEVSRMSMJDQWCBJPXFVSFHJOOQOATFIXJUJQONMFMKVEAISKVFHLABA NPLNXYRBAJAWUEJIJCODLUMEAIFITOVETRXUIVMHQSWQRKFCCNJKEPJRCGNOTIHLNVDCFOYMPGL OHBJOWSRJLVJWPTWPMDAEQTNAHMRDSNBWSUDHMFPWJXJCMHVTNAQVVRXMNIGJAOQXUMEUQODGNC",
    WhyNotMeasureEffectiveness:
        "HMDLYPSNQHGCSXSJWHWPBRPOGNBTHFFNGYAFSDCETJUIWAPLDFFGCNAPVNFLNXFKBRUTXMPSFSV KNHDVYQFIBXIWFAUPGXULCXQFBKCBVDXJUPPICFDLVTBDXWVXPFGOIJIPQXTNODLXAYBOKMNAUI ELOVSYTVOJPQCCEUCEMKNKRNLPHOTPYHXGJXNKEYGLBHCQTVLLXWKYBSTBKDRFCYKHRVSFGRAME",
    AssessProportionalityExplanation:
        "AJOXNTIWDFSROMCDQHUKSESMAVWRJCNQNDFRIACPLFMUEVIBQWDMNAMUQBXQWPMBRBELGJUPEFX WIFSWTCKJYDHUUOGYDWRVUVRMFATVHCNGYQVMGSXHBFMJGCFJNTXRDHCMNGRSINCVPBVESSRJYJ HOCCPOGNBPCSPTIHTMARPSOMPOFXPCTACLIEDYCUSPEJQWSSCGTCRUAOYOLBJHWYUBQDLEEUKEY",
    DidConsiderLessIntrusiveSolution: true,
    DescriptionConsiderLessIntrusiveSolution:
        "XQFFXSAVJMPWJYKAXPBVTFOQAKOHCNMTVYTKWETJIDLTKQXBTVLNVIUSBOFNDSSVYVAJFYCTVQM KVQSRIENGBWCOUROWGQYDBPQRNBNWPJEUBQERDBEVXMTAHFDMBNKLCWJFYADGPPQQRGMDNVSELD PJNBQENQCCTPBURGTCOENXAROOKVJGDXMQJJQDIBLUXJECVKYIWEBRNRIVLBSQHVXVCKKIPQSMR",
    WhyNotConsiderLessIntrusiveSolution:
        "KTDWKNOJMGBRHFXVQBIVBSRSUTHRLBTUMJTVLYAWFQRNFTBVDDIXIFEQCJCPGWWLMFEWKCKQBLP UAYMMCHPWRBOYJVJPETSKPPPVWOWGAYWUBNUMDJTBHKFRTGLEDGUIYYFKJPPNJIVRDSXUAVMTYQ JHTCUKRYHDUIGDDTSJXEKRGNKVJOPYGJPVSUFKLEEMIQMLJTWQTFSTJRAFQXACIHVLRKJINIXTA",
    ContactATIPQ317: "receive_email",
    UserEmailAddress317: "GJKALTMLBD@gmail.com",
    IsHeadYourInstitutionResponsibleWithPA: true,
    ResponsibleComplianceWithPA:
        "WAVPGXYNDTYDFUUXFSWYDPXAAAPDQGXCKIDRICFNGBMODOBIEKMLOKDHCVPGIUWWVVRVQCODMJR MNXLIVAOHVMMJMMUHRAWOGGSCWWRIJUBYYSPRJURIOEYOBENRCMRJMEFHEJLYHGXALMKTWDWWIN WGSNAIJHGTLJWJLTLKCPRFFVRUUNIHGRVUBMFDWCODDAQAJKTJFFJHXQBVUFNUXYMSMCHYNINAA",
    ListPoliciesAndProcedures:
        "GJQTRPGBQUYNEEIUVKSBSSCTHIFLQPAXHHUDQAECYVOOFSELKWRBHGSMGVLJJTJAUAFVJFDUGPB KLVJXNFPYCARKYCWDFFSYFBUDMXOROKISIOSTFSVHIJWBICHADLSVEDEJBGKPPWKQQXCJICWLIL KLGTQYALWAXWNMXTGAPAJVIATTVOKQGGTARWOBYAWJGEEPTOICCWXIUOCFYVDKAGTQDMUAEFBOD",
    DoesStaffReceivedTraining: true,
    StaffReceivedTrainingDescription:
        "UCTDWHOPPJPRMDLVDSKFTHCASNPHCVJHJIDDQQRCOCGGIRMTSKPUYWFNATJJRHNTYHHEAHFLAHP ICEKXJXFMTPLYBPROUQFKCWRVOFYJHEFRDAFDLMQTBTTWIPSPYPLPLKFFMNIEXUFOJTVAKODHAL LGGRVGEUIUXVUXGBTDHXRGYDHMGELTIBREYUDWFMDKMIHJQWCKEIPRSFHCJIYAIOMWEPXKXVXUU",
    ProcessHandlingPrivacyComplaint: "yes_in_place",
    ProcessHandlingPrivacyComplaintDescription:
        "OQHDLTISFWPFNSTEWOOFXLNMCLSRYCAWQDFKGOBLWPSABDONULCESIGCDUBABPSCWSOJMIXHMCI HTLHJSBQXRXQKJKPQSWSDUWLVSUAGWDDJRRPQBCNOBULUPKAEHPSSEWMWYLQXAJBOTGSRTXPPJD WBTMWPXKICKJDOBHKRTOBFSEHWCPWALLMMCCQQMPDFAOMWTUMESKJIJQHPEYMHMIPYWPLYQTFEK",
    HasDataMinimization: "not_yet_planned",
    DataMinimizationDetails:
        "SCSNVRQPQPWCTJEVGBSWDDGUDVJOHISCKWPUYUQERUHDYEBKGOUDCEAOUXKYICHHVUQVTJVKKNE PLXFWVMVVXUGKSOEXTAKXWXXUIRYQQXMHVTTQYRBNKVNIVQJOUUWJRJRMYKNDNFEAHXNYTNXCXW DGRRLGCFXQXXUXQSUEYIMQTPUIUGNXLHKPEPIGSEQAYSOVINECGQMEALLCWDKVRYEPNFTBJOLTQ",
    DataMinimizationPlannedDetails:
        "SBEFHQHXWHGIKDXPVTIPURBUWARVJEMLJKOAENFVHVCLXYBBTDERAROAYIHGYKNSUUXANWLINLH DTNGYRRVTHSEOTCHDMMMMIUXPYLVXVHKRTXBGFUYIKXTREMINXTOVLPUXOPYGUXXAHMUUBBWQMD CDAYSJHMTLKYVAEGAHCUSHBXDDPOVALHSSNISSYDGBYEGXEFFAQYRUFUBBVOTRPSACGCLVMGIYO",
    IsContextualSensitivities: true,
    ContextualSensitivitiesDetails:
        "AJNUNDQQWQVCMVBGSEUIBSMSWTGFUDMCMXEXUOANCROOEPWKHWWUUBIGWTWTWLVTDSOORCLEEGF YYMSNJKSWJPXSWTSTIHERKJCGJQEJFXRUQHEPPUEMFRMKPWUHGXDRIKOOKLDSFIQKWDCPODDNDR AKGGBJKVTCDXUJTKODBBGXEDVVMCXTASQVQUTPPNVMBVLRRBFGKEVYOCGDKEVHWABKGXSXPXNME",
    PersonalInformationPhysicalAndOrElectronicFormat: "physical",
    InformationPhysicalFormatDescription:
        "MTCBODYSAJRYSJJSRFRQQFCQGQDFXBCOCDKMPAYGKTSUJGMXVWDSMIAGQLTWYSTYGCVOXWCQGLG NQMKRTOFFTRUFWPLHLUXGPKEDCDOFIILOFPVLTSMEBELJLHGAFYIVJQXFHGOQYAWLGGAHTAMSIT HNXJDQXXIVQPQXCSRGKFHPFIVXJNMDULOBVJBAMJMFBBPILGFMJIUKUQHPNFGKKEBEAOBRQRSAS",
    // IsPhysicalConvertedToElectronic: true,
    InformationPhysicalConvertedCopyDescription:
        "IHTPLLJRJNPGSAGYUBMHQOENHGCVNHXQLAYADCXCKPOUNNFHWGKKXNBTDFIEINDBPXTRBGURDJV UADUEJHSJEAIYKXUBKQJIMTIMUTPEFSOCYUIKSCFXKMQDFYLFBJDMMLIFTHIPQNDKLGYPOKIHKL DYXKPMGWSHBHOXXOGOJYKAJPPKQWTROGVFDRWEXXWUPXMBOMIHDVADECOHTFUJDASULITFQBPKB",
    PersonalInformationElectronicFormatDescription:
        "HJCENVGNISYFQPMCGXAOSKAIRUGMWSAVYHGXCEMIJHATFFIUIEHQPDAWISLSPSQOSCGJJOACLQE SDRCXOTDWPTCEIXMGOOKTNLHRMQNPMENLGQHBDHCBLVJYWTGCISSYSFFQKJKXGMKLGQXRQLDHLI CHQYCJRNPXNFFKPSBFLAPUMWWWMRYYMLEGVMDKRMQVIGPSTLWKCRLLNGTTCFWYOPKBAXOCOPNXJ",
    IsElectronicConvertedToPhysical: false,
    IsInformationElectronicConvertedCopyDescription:
        "CLRGEUGAXPYOIFLAAWIVJFSUSJYQBTUKAGJPAGNCPJJXOWNSILOMBSAVSWNTVOYDUNNBUVYTJFF XCJKQFRYDYAADLHCMYCGWMLSNWCQHLMHPYMPMQYYXJVFHWQPYPRBHJKKQQVSDBRQMRJEXQOUACI ERHLFYMLRMMEVLJSFGNKEOVWEQSATWADXIEMSVMESXDRHQSNQFVJLFBOUKHOGLQULJFMHVYITIQ",
    IsThereCollectNotIntended: true,
    DoesHavePoliciesProcedures: true,
    HavePoliciesProceduresDescription:
        "HJXVBYYAAERMWCTQXGDXEKAYHCTWDXSJQVYNPPHYSOJAJSWVTKCBFWHWIYOYFBVCKIUADGBIYDE LVBBSRLMIUOQLGBVMQNXPANWPKCOUDTWPLPCMMKOENMRXWREOCQSJLLKIDLHPVREARAAQXIAFYT DTEJAGPBIVNQRSSIKRGTCUTYGNSPFQKAQRLPDJLUKQDXKCVEWHHWDCLIAFCMNYVQLNYYHCEBFKJ",
    IsDirectlyFromIndividual: true,
    WhereWhomInfoCollected: ["indirectly"],
    WhereWhomInfoCollectedOtherDetails:
        "LYBTVDBNRINDAYIBISKDFEQNYHUCOYIEUJITQFVLUYUJQODOEIUOMKRHHMUOHXXSAJIPPOJDWXI RFRPGTRTCTXCKIBRDMWRLLSXCLTMLAFTVUPTQBXMLBDVWLIERLAMCOSGMSNTAFHBNDFOSHBCOKF QCUYFHJUXNHXRSSTRCIENQYNOCCPDEYIYPHNFNIOUDJYTJOLYLLQOCUYDHKCESQTNXXCLFODSSI",
    IsOriginalPurposeConsistent: true,
    OriginalPurposeIsConsistentSummary:
        "QNWWVIMFNUDXKKCDAXQNUGTDVICXLYTWBOXUSWUUROPIJQGNYOMVLKRKTSBMFOTOAGWUMHKCCVU ENBIGNWOXOJXRFHAPSWMQOFBOXBRXCRFEAQBDUJCCIWCAMCYAPKAKELPIYSHLFQUWDTROGWTIUK HJNYSPYFKNMDAWDQDKRGNUXGIADLDLDUDGOYVOYJFRMGMLAQIMOWOKOMKHQRLMBXJQYSIDUOKIB",
    OriginalPurposeIsNotConsistentJustification:
        "DHBEYNFOQUYUDRGAFUWLKIUJAFBYGDMAWYWUMRYECDGBATHISHLKWXUTMRDSMFHNHXXDUKNMVSI VQILFHXYBWROYLOMKXVKJUYMYJMSPTGUJGFNEHHIPECYHLUTLPGTQIRARUMUUFIHQWESFBICPNU KORSBEKIORHLLWLSMEOKUSJWHFPQEIUNRDRCSRTXPVIWYXMEJRDAYKBRFTLVOTEGWSTHFIYTKQT",
    WhyCollectInfoOtherSource:
        "SSJJYWXFFKGUGMCDRHGAKVBTMTQPGQJWMTFIANAYKDECSAOMOSNYHMJVROWFFIXOAJIMHSCEHGP YIFTDVJONWKECSGDRVAUIXWERYJDLEMYJSGADCPQBIUBNRBTCFLALNIBLABELGDJJKUILGAOGJT UTOUKAWCXQBSERWSPJDKKSMUQKVRKXRWSPONIYMVGEKAQPNVOFMUXSPBGSEAEERAYEYNCIKQWGE",
    FormalInformationSharingAgreement: "yes_not_established",
    ThirdPartyCollectionDescription:
        "YOVUCEQTWIPPIEAFBIIGRLKGOLOMJBTEOVIJUOKJIBICILAYFNMDUSNMDPGQPEJVOLAMVQJMXYX YUQSCESFDTVQHKIGLRNGQMBJODRCDDTLQQQKQNKXGWPBIKTJNKCCKTLMSGEYLPBYYJAPSXPXHOY QVDKXDLGFRQQCJAFHKGCGANXKDVQUCEVWRMHSUTHGNWJPTMYAJYBMOWPIEAUGULDNUTKWSLMPYU",
    DocumentationRelevantISA: "upload",
    DocumentationISAMissingExplanation:
        "SKFXUKRVUMPGGOOPTEPUUQNKTXVEIJSDJSBLTMPQTLRBRPQXLJFMXHHCWUDWONNLTMVNMDVHNXA MKHGIBESOSPACHXCAERRWJYESEAXGQCVMEAKBJNUBTXASGAARFXBLKWDKDNDAGMXPTNWGMAQPWQ OPDNLINVSOOIUNKLRSBDMLPQQXSRBHHILCPQIUIHPYHSNRDMDDVDPHQDALVNOVTKHFWSXTCWJSM",
    ISAFiles: [],
    HasExistingPIB: true,
    ExistingPIBDetails:
        "VSBXSWYYOLOSMAUBKTWDWCCSQJJTLOPGMXLHNKUPWWIJLBQTGVDGRKETPIHIMFMYUHGOONMYXHF FPTBQKCJFCHWKODXEQOFXOXMDULCCPPCFHTVNXCXQFUSRXPXAJPCQVIPRHWVYYGPLFRDTHJGNPN FWUEYNNWDWVOPCQWJJREWLCJBGJBSDQCWCVPSCSJJJKKQXYSNEQBSKDTTLCREMEYFTRMGBDGQHU",
    NoPIBStatusReason: "new_pib",
    HasNewPIBWorkBegun: true,
    PIBStatusExplanationType: "text_field",
    PIBStatusExplanationText:
        "NIIPRTLAGNDOYVTRLYRCXTBFDLAVWQBTMWFVFUCIIWAWYBDSVJTEJCFTGDMGSPDOMICCQXLQVIT YINVLWGNHBRWVKTWLMDAIVJPRIFAVYUDMKMWOYSYKXPLCQYAKCXTVFOCXXECQGRHGNKKXWILSEP MKUTWIOUJSSGKUOIGTDAMUYKGBBQKHVLTEIFQTHLAOTWVUONHXOPXCNQKKMVHXKBWGMFLIQLMQA",
    PIBFiles: [],
    NoBeganPIBStatusExplanationText:
        "OMBLMIETEDMGMAMMSRLUDODLWEVHGLDNKRITHXEYUYSDPWDOPAIDEPCAJOOILVMRAXUTRREUNLY GEFQUHBPXJQJOJUEWTVTTKJXQSOGBNWKTOCBGIMYLPHRPHRITOIMFLDVUGYCRUNJLGPYHTWOHWI AWTXAKLHUBKFEDTNVMNUOIWYFTWSAUJPXYLABTSAHOPTVXCXXPCNTGHQYTRGNRGAQUHERSLCTMM",
    WhyNoPlanToReflectNewConsistentPIB:
        "KFKFXCOENCQTYDOWENCRRMGSWLRIHVVVCEEHWDQOAEPHNTYTTFAPSFSWYQHMJFWRFTQUXHABVNR HCTKMYOHNRADJWEHHCSDNSHWIAVXROGWAQTEBOCYJWCTKROHABHNMBHNUWBLCQOXLDDRCAGSYSS APIMRSAGQXQFHCQTBKNJKIQUKLBCOXRNRCRDNLHROBIHDIAUTLNBPEBQXMBGQWQSFDMFKMGPCVU",
    WhyNoPIBExplanation:
        "JYSTCTDJAJDHLNVGNNJAIXJLVJSEUDHNFIVICXLPYUHBMDJCFVFCUWSKOHWRBYOVCOBDQMDPBTB AYOTMWWITDFLRYYOLRNXKDTUNUKJWELTXCEXEWKADJNADXWRTQHAIXTWFTGQMMLPQKMPTBJNGNU BQKHNQXIXDPLQPYYXFQIXOKOJUMGTDDUCAPJKLTNETKTOAQULAVFSRULGVXREROTYTIQAPNLKDE",
    InstitutionNotifyIndividuals: "yes_already_in_place",
    HasPrivacyNoticeStatement: true,
    HasDraftFinalVersionPNSAvailable: true,
    InstitutionNotifyIndividualsDescription:
        "KWYIIMNSLFACEMNETMXWVRKLSYSBEYGGWAPMJNOFRTTLSLHKOUKDGUORLNPITMOMYTFEWATFXRE XFIPBCWYODMHIXFCJURRXGDKQEWLJQDFGVMGTUIVRUJUTOURQPYNMJPQBWYVELPWYGBMLYHNMUY CDEUXUFBNFBLSQJMXQPTRCOUVKAGMGYVYFJUAMDHOQBQGMIIKCXQNWAANIYMTYOGGEMMHOLLNHF",
    NotificationTime: "before",
    HasLibraryArchiveCanadaApproved: true,
    RecordDispositionAuthorityIdentification:
        "PNVLPUWTTCPGWPTGEVOFPRUQROKWXBHOCWXRKTNDHLIEMJBOQTQDNPFXSESAKYVRTAEAQCUJILW UCNYJBGXCABYIJVSFCCPRMSOROBRLQNDWFFTJOLFAAKUHYTKUNGWUMHIJXGUANMLMXCDDBIQQVP VLMERETTDRXNCQQLKRALWXLMPYFKVOGRTLNLTLQGIEXDVDWEKGBOECBXYAORYIWOKGTPDEQYATC",
    HowLongRetainPersonalInformationInPhysicalFormat:
        "FKHWIKGWIIEYDKOJMNOLCNMOSWIMAWMJMQHDTOILQVSAMJDKXEFOHVORXSDKCTVLVTLLCLPXFDU MPLGCWSAKTRYMYWBQRDSVEBRWQSTXIEONDVNBXRXGJLMEOVUTOSCCKMIOSILEYCBPCLICJYSAEM UNORFTXFRUEBMRONWVTCSECQAYVWDAXSWJEWIGPCVMCLEBCXVCAGGFEPLWRFWACRWLDCNQFPGQG",
    HowLongRetainPersonalInformationInElectronicFormat:
        "VMUCGEKFTDKJQGDTKELWMPRKVTEFKSFKROIYKCLCVEWEDGCUXGWCHKTGTJFMAEUBWARBWDJISIA ABANWPDEWOQUQNGWANMLLHWUUHDRBLMWAGQCTFNPDNBDOXMCCLCSKHRREFRPMLDKBSTJVDDUAVH SOPGWMWRESDOGIPIMRNNVGUGWOIKJHGUPFCSVCHAGVANEHFCDJTVXQLLTJIIDLIWMIYBGWMJJNH",
    ControlsProceduresImplementation: "yes_in_place",
    ControlsProceduresImplementationDescription:
        "RGMJPFDFSJGBALCTILMONMNSOTYICOVMKGFKLMFSPMQYCKAPACCKNMTESSTVFUCDMTQSGQHUGTX HYTKTMXQONFTMQGXOXVYJFEIHDXPSKHCMOMRUXLLHJYMTEBDWJULCHYBULCPNIXDFDGWEOCQMKQ RBQXXFMMMLCEAOPNJHKPTOBMYFVJXMINCRCDGDKOVWMQWILQTBXRTUTCAEYSJDOYDNBHLLHGWUS",
    WillRetainInformationUnintentionally: true,
    WillRetainInformationUnintentionallyDescription:
        "YEAHKGVPLMNSFVDDBCMFCKSCNAHQBKWNWCEQDQCLPLCXVKVBHFPELBNNKXSKYENAPYUDQMYJAAO FDQAMUBHYEIYKRJVPCWUJVPPSSIDGYTCGRKXXHNBPJVREIRWHMTEYQUJMAGTLWAYKFRRHLXHNVF HUMRYMLXIAKJLSLHENJEGKJAWAMILCFMDQMLYUBBONMOYBMBGILEYOGVLMTYACLFTWFUGAIJLIO",
    MechanismToCorrectPersonalInformation: "yes_not_established",
    NoMechanismToCorrectPersonalInformationExplanation:
        "IBLGSIJAQHNUJUMIASWRMQDVEAYNPMUVXCCXXJPSGEALXGGRHMBOQOKRWOCSIUKDMQVGSNKPDEL BVSQLGPCCSBQTXITNWGOAUNQIEVDVONCXUSVIYNJHLABHOJCCOBVIRFGHCIHKMGNFXSYFMLOIWG ISAXGSNEGINAIIQSUAKSRJUALRXAKWVAKTEIVHAQOGOKCSBGOPHMOILYWYMNUNTIMMOODHWNATD",
    MechanismToCorrectPersonalInformationDescription:
        "AXBNXNQPVBNTDVCBNFCXBCUCTSOCWJHSGNMMWSMHGWLDOJAQYUIJDEUWDXTEYOSMSTNOJODTRUQ WFGPKLFEPOWNMYPPLJKWVEYAHYYCPVCOENFUMSPXQXEMGKDHTIFFJLBSFGILLDNTMHIYSUCRTLG KQJAEAKJJPDBRVHPRTJNQIDUXNROTXESVTKBYDPWOGRPUVTYTIUDDSGBMNBQHVOLLJFXKFPODLX",
    WillProvideOpportunityToAddStatement: "yes_in_place",
    NotProvideOpportunityToAddStatementExplanation:
        "FMNYDOFFJFIBLGRLEHBPRUFXAWWLFKPLAXLDHTSUJYKMCRHYRKPYBEMJGPYFRSYYPWAMUNDJNFG QNLLOCUSTLAVQFITGLGYERSVTMSAFJQIUXJEMMYJHLHDLNNNURGYMDBXTPRCIUNKTRBRUEGSMVQ IJWPFXKUVGTUMDEYJTPNEJAUKPTYDAQBQMCTSAHRVYEHSDYIDVQSPIAYJBFPDLRVORDYAJGJMXR",
    IsCollectInformationAuthoritativeSources: "yes_but_not_in_all_collection",
    CollectInformationAuthoritativeSourcesExplanation:
        "HALRPAKJGVIRBFAGFDGBDHDKSUIBOAEMCQMQISHRPMOVYNEPRONOIIHAWBXTRITFQVOKRIWMUOL UBCJHYPNFRQBTPADAIGQQMQRYBWCLURWYTYNVJSJUVTWWDKJJJNXTLXHKKKFBNCJYSBAQMGPPWU BIADRLBNINWPRMBLWQIFUTCYSMAURMQITRBRKIKJOKBWVYRXATEBHXXGGAJFKGVUWNUALIBNGYQ",
    ProgramAccuracyDescription:
        "HASELNEEYWKEJURAMIRHTYUTTMBDKBECNHEXHWOWVRRLVLNSFUKFONLIEYKXMASXRIPBPTSOTTL FHSGSBFFEPVISIBYPCDQPFAVNAQCCDMXSVWPJROYOBIIEYDPVGIERWVAHVSRKDCBDWOVLKPWNDC LVLYUNAAGMPRVNIUDLJIYHVWSUMXPECPIDTLQSPOAVKHDFAHNAARNHBDANGYABKCKAJSSWEJUTH",
    ProcessDisposalPhysicalFormat: "yes_in_place",
    ProcessDisposalDocumentationPhysicalFormat: "yes_in_place",
    DisposalPhysicalFormatDescription:
        "XLJFXSXAKJMYKGPCUVGEAYCCMEGFXPVARMOEMAHFWVEUTSVDQHTIQKWXJGSTLRCTMMGXRKOTNBG DOPOOBLMHIFWUBXIXSGVITKOFCKRAGGNHQUJBXNGBVBYRTALQFDXWAIJEAIMQSLBCQPDGOGYEAT TNQXUKOLUASCCIVQQGGRXLANWIFSMJBQGRYCEGTIOFQQRGPJFAKTWDWINCAMEVXKYBUJJTMJMWC",
    ProcessDisposalElectronicFormat: "yes_not_established",
    ProcessDisposalDocumentationElectronicFormat: "yes_in_place",
    DisposalElectronicFormatDescription:
        "HHTMTGXBGUDWLXFPODQQMCGQTJQHTCUCRKHKOCYIEETGYSXXQTPCJUOEACSJOQGEABEAQTBMDHL FKIYDICIRWUGXMEVGCYNSYNRLREMFIVALIQBLPNWSLJKIUURSKYIWGWGVPMLEPCJBTTOVCKQNCU LYBATVEDPKIYOPOMSKARFOLLSPYYFGJJRVNXGQBSJMXTEUWAPPFYLQHVNPHEWEXJAYHRBPGBIHI",
    TriggerProcessToDispose:
        "LSRJNKHJUAQEPDMESBHLAVRAAFQQRIEUYWPPLATUVKCPJDIPWIHXUFEOBQJHTQQLUUERMVRRGLO SXSOXANBXLCUMRWKODNLYJCORKVANFEGUBXFGAYLPGFONHVQGVVTAGNJUDVMDNNRHUAKSQDOEBV BJLCXBKEDSVMXAAGNCUBKPOIDSEKEMNLWJGTHRGCEVXWEUWPEQACKVMKTCYEWYYQEKONTGXUUSV",
    WillKeepRecordOfDisposal: true,
    EquipementDeviceDeleteStoredInformation: "yes_in_place",
    PopulationImpactedByUseOfPI: "all_employees",
    PopulationImpactedByUseOfPIAdditionalInfo:
        "MQRETRKUOJMOUIMRPRYLMAAOEIXPVDDTGJTRMABLCXALMSMGIXUSKPSMQCYKTUYLGSHLOUFOPMJ CIIWGFDUKEGXXYCVYONHBSNXCEBLBAFWKBXREJVOEAPEXMJWWMTXEACIUJUCERSJYJMVBJRPSXC UQHPTSCEUFTSLEAVPSRMDWHPGLREDNPUGWEHMNHLXIWGRYIFLNSHFTIWJQJHBWBGOXMNYRIBLFN",
    DoesFocusVulnerableGroups: true,
    FocusVulnerableGroupsDescription:
        "OEJNTJFILQRCELVIRXCLSHOUANYABETNPAJELGDLWBLAJUSBRGHKTDPHONMGJEGHVEMEBRVLUQN MFXLVPOIGDUXAURTAPVITOSVCGAXPKHHWLUFFOLOLCONBNPOYSAWOBSWMCIPPQSUUMBOYLOKDGV VNCNKWCFJLAEUNJGMCTMMJKUNVEBBEOTMGLVBRJQPNRMNBHSCLOPGWRMCHANSADFVFRNCMETSCV",
    SizePopulationImpacted: "small",
    HowInstitutionUsePersonalInformation: "administration",
    HowInstitutionUsePersonalInformationMoreDetails:
        "HIRPMJYIDWEDYBYFXICHGNUBULMPRGQOMVLROMREIASJVEUECGPFKTLTMQTAWIQWGOQCPGQLPWY RSMLKJYCXJDJHOVXEGEDFNGQLNJSINBKURMTLDXOTOKTHMEWJYYHWEHELVAVAGTJISOPCCLAIPI NWTISJUROPXOMGNIGFNBMHHWURXLGBRRAECDOTAMLPGQPVQSBCWUFTPGPVMBLJLNWGOHDKSLEAP",
    InstitutionUsePersonalInformation: ["purpose_collected"],
    PersonalInformationUsedFor: ["profiling_prediction"],
    DoesUseDeIndentification: true,
    UseDeIndentificationDescription:
        "LVIKMDPGOAOPFUFQQJWRDVSLTYSHAMMVFOUELVNVBTONMERXNCYWRKOOCWQNKIFCMSJPYAFTVAP QJHKUCEPXITACEOGIIXFAPEOQBJBMNSJWLTYACWPXRJWEXDEXGRPTQRAFRTTRDDKOKCQKPGGLIH YFFWXFAMUPTNEXDQYLNNEQIPDSSHFFSUBJDWMNXUJCVPPREWORNYGPKHVPSEMRHOWXLTUGELMRD",
    IsCollectionReasonOtherThanStorage: true,
    DisclosePersonalInformationMethod: ["legal_authority"],
    WillAllPICollectedBeDisclosed: true,
    InformationSharingAgreementInPlace: "yes_not_established",
    DoesISARequireUpdates: true,
    ISARequireUpdatesDescription:
        "YAYMJGJXFGTXTMGSDVRPPDFPXXHCWKKJBNXLPTCYITFPQWTUJGHSVYWVUIOKYHBTUJVFNTCJSSG JCCRJQQAYNVCRVTLBIMEUNPGCTGLWVOATQHLANMPGRQJQVHRYOQEIUJVLUOOKEDCXUIANHKMUVX UIIUWHSIXHNICYORKUIGFVGVJAATYMQDFTUCOSGWGBWCUKLPOVJABRYXCMKVHXILQJCHELDRNKA",
    NoISADisclosureDescription:
        "CEWAFIKJWXEVQXUFGQTIBHGXCJDUCNNXSDNAMECTFKKBDCYJSGCNXPNUWXWVEPHIJGDNKUSBOAD HJROYLYQLPKOOIPFGVPIMRLNSUTBATJSUNXFXOKSLEDEEDBNDQFOEYAPXEUDRXPRGQSAKJHQLVV HIOWDLQYTNCFWXPSFLIIKBDJXFRMPEYQYJSPTMEIEQLBDTYTFRBMJWRGFFXXTEIPOKFMFAXRHAD",
    InformIndividuals: "yes_not_established",
    InformIndividualsCommunication:
        "RTAGPOJOQSFCPSEEYKTPRDNBBKBPLIFXHDECOODHLWRQJDOMFXQAXQROGXFFMSDIMGTLOCOJGLE LMAOIVQAOMQJHJVLUBDOJVNLRWVMQIRCVCVVIBVXOLUDNKJELGDYJVKOXOWLADIFTOMFNACTFFY JPRFMQAHWYJSFWLTBHCQYBKHNUSHXPKAAFFMCMKYLFXIUJQBDEQPBQJIEJQRXSIHNJRARXRNWCF",
    FlowChartFiles: [{ content: "3916", name: "css.txt", type: "text/plain" }],
    HasSecurityDesignation: true,
    IsSecurityDesignationSameToAllPICollected: true,
    HighestSecurityDesignation: "top_secret",
    SecurityDesignationDescription:
        "VYPFNKPMPTQECJHWGPAWEQMQAMSUSQYLRVEPSPUBABUPQNPSQLSXETMFLXEARTTXUEMFEQEQUXV BVLYEYMYPKUUNXCITRSVEMJMQKWIGXTVDFLXJPGILPFPRFFBAKEHRXYOLYISCERQPXRHLEYDKJK VGOXVUAWVEFYQLFOYFIUAKAYWJIESCXCRWEHHGOAAXOVGUNGOAQUYADKFOAMMUETGCHSGWGRQIU",
    IsPhysicalInfoStoredMultipleLocation: true,
    IsElectronicInfoStoredMultipleLocation: true,
    StorageManagement: "some",
    IsInstituionManageStorageOfPI: true,
    DescriptionHowPIStored:
        "EBOORDUAEBNLKYCCIVIWJUWIVECDDMJYOTAAOIXFVSSVBAKEIAAAQSKIEFSMAQWRROWQXCNYWDA XIGCGEGRTCXCOCDEQGWVRLAMRRKQPXHDFJXGPHYLPFKDFNLUSKTMKXMLISKNTOBVTUWFEWOJGKG IOVCEIKXPPCTRSOXGCVCKHNQHRMGCYBWMSXOXNWONBIJRAKNFGQXXCKBAETLUEVQOEGYTAAREHO",
    FormalAgreementToManageStorage: "yes_not_established",
    DoesAgreementRequireUpdates: true,
    AgreementRequireUpdatesDescription:
        "TUATBWDMRPDNCFMRIIBVLNQPVVJGKVAFJVIWYVUSABIUXYIEHCXYFRVFEKXEMWBVPWEFWORMMIU SXUUAOSPXOWGENNELRHYBADYPMGXJLNTWJDQIVXKHKCFRHCIETHELDFRUUFMIUGLBCJUKWVPTVQ RCGPDJMDQOOVTJUGNNYRDXTBRWMSGKXGQHIPDUKXDMGIKFCPORHWVHYTHFXGVSWGQHFMBEDRCBO",
    RelevantAgreementDocumentationType: "upload",
    RelevantAgreementFiles: [],
    NoRelevantAgreementDocumentation:
        "IYEBINYKXQODDLAJOLCRKCPSFLTPGUUWKWSEYSHSKJSHSMDARFUYUJBGJLUVTIDCVQRGRUJVDJH UQRSRTSVHBERRPOERDEVSJFLVAKIDYHKHHLAXIOAWNJGHNCRIITVEAWLLFVRJKRHTSJJENFIOEY XEMAUCBWUXJMWFDEHUPSPYOODGNGECBGCQGWAHWNLDIAAEOVHQCHWWAXPXVOOTSRVCJFYFDAXBH",
    HasAdditionalInfoAboutStorage: true,
    DescriptionOfDisclosure:
        "MDACJOESMXEEJECOJUVSRLDOAPDOACFTYWSHNYORQWLMXAQJLSQVRPBAYKCTKPRJRJELKTBKFDC AXVCVVNXBONIBAQOJTRBVKXVBBCMRXMYSMPHXHBCRQKHHSCCFKCQJTSOAABUSBFCBNONKIQCRPJ DUXKNNMRLVXUYEUDDQOWKRYQBVRDAXJXNGPKDKAELIHPWFPFWUUMNFYLVGIQVIQNMYGSNJYRPKL",
    IsStoredUsingCloudService: true,
    StoredUsingCloudServiceDescription:
        "EYAKJSSPUSTVIYDRYTIJBCKKYIYSHPUYADHAKRNSEMBPGCWGYGLWJVNBNOLATAIEWTUFRCGHFOE GQEXVQKPHQMNEUWNUJSELDNECUEWSTKRYXHKBIUHHTBPIRNKMYADBJLCDYUBMNWNGTNGNLLMOLV SMPRYOTTDNGTCPOMEICJOYEQHLFRDVMIKMBYDEKAIMJQMXCABATGKLYTHYKMIBPGBWIPNPIAXCA",
    DoesPersonalInformationLeaveCanada: ["temporary_basis"],
    PersonalInformationLeaveCanadaDescription:
        "RDGXDDYWUAARHSNGXPBMCIAARPKOTGQTLTOWNMDMYYBANDJOBFBWRVTICFFNRKDOJFFNEPSLLON WOCULKKEMGMCMGAMIMEUDSPYNDVGPQBSFPAHXGFDVPIEFLFDJEJVFKKEYDGINDNVFTWWGSNCHBY GPJAOMDLGTEUHVWVHHJYWOOCFTUGLFYKHXPBVYOCOCXWEGLIKTRGYKIRBHUURVABUTNIGVAHRHJ",
    AdministrativeSafeguardsImplementation: "yes_not_established",
    AdministrativeSafeguardsDescription:
        "YBGYLUSBSTDNAMFIRTYCXHWHUMONHKTEVHWVPKLOAMXKBEPLLDOTJJHRDXEYFFTIAYQRPIRGIKC EQSTIKRESSDPFPCKSXTUGASGMCVYFOKWPDCIOQMHWBSSCNYLNFMEDXPEXLHGNSXDIGYBMTVBKLX UHXRCWLPMKRYNYSRYOEOUDFHVWKSMGGAEJEBSEQNXIYCWWQEXIODMYCQBQUELSDFDRUEURXTXPQ",
    PhysicalSafeguardsImplementation: "yes_in_place",
    PhysicalSafeguardsDescription:
        "HCFEDRAGIGCEXFHSAOJGCWNYPWGQYTVNWSDUGYJLCWULMIHUJQAVEYDKOFNFLJGNJNGFBMLBEXD IHGLXSRTNPFQPJFPECNGYQEAXCLXCGJXPAGAGBBQAOYMJYVQLVVAVHARCGNUHSQHFHAPCEIDAVG POAPEHYUAEQALSCNVREWTCADUMGHRDBXYOKNMJDTMATPRROAPLDMUOQMNVUQBRDWCRAVIOALNJJ",
    TechnicalSafeguardsImplementation: "yes_not_established",
    TechnicalSafeguardsDescription:
        "CNYAJMFUJTBDPUCDRJOVAEKSMHVGCGAPSDQAGNHYTIUWXKUFCHSRDWFXDFNCQXRDTKKLECWDCPB USSUMINYOINPCCFJNQOEQCPDMYXNEBPCCDKETEEAULNRULKYWAADPTOSDOHMKYUMSKMXQAPJLNI OFUYXLNSBCDLQGWTTDPNHIITCXGUEYYITXWQNSSEXJQPBPGSMANRCTIGVBVYFSOBCUQSIFGAJLO",
    HasEstablishedWhoHaveAccessToPI: true,
    WhoWillHaveAccessToPersonalInformation:
        "JIXBAHCJGPFLEPPQGGLSOIKSXJWOATPCCWCVHRUKIFTDOGYVLBGKNQIBXECQJNJLYDIGMSIOLBJ GNADFHTAMWESOQKXIKBCXYXXYRLWBGIPBFAWPAQUCVFPOYHWNXBPCTWHPCENUVYGONQIQNHHTFA IREFGNHUFQRWHGFECYJNDLRYCGMSPBVSMCFMKCGVJHFIWDMGTIPCHNPWYFCYANFDUYJEBSTASNE",
    DescriptionProtectPIAgainstLossOrTheft:
        "VCBLXDSXFYCUXXMOSMGAVIJXPPTDHYXKDIPJKKQDTDLOVTWGSBISAMLMRCVIIPQFBRROIDDHVDG RIRYMGPPOOBFWCVRSWDTAPMBJMMNHFMWICKQCHNGPLJDMVIGPYIKCKYCUQOATCHICDWUREOLJWE YMBGWGHEYYMJSKWXCMTDWVDCICNKAGGGMBKSXMPMSOSHFGGUNAPBGHCDIYWURVDSSGVRADYOWHJ",
    MonitorModificationOfPersonalInformation: "yes_in_place",
    MonitorAccessDescription:
        "KLFICIEVSCFLWCWKBCOEJYVVQOLVNRRXYBRICSNNFLUIXEYFEUHACUPLOJQNWIHBKGMUJOIHOAY DLHUUCRPWURSQUTTQYEHQXSMQJTLUCMDFIFSIOWXDOJVNGCHMRIXQBRFRTDKHFUTHOMIOAKBCFD OHVFAXPBRPLTDKFSGDLBIJFHPHOMLQAJUWYMYJPGFGQAFEKGAQKILDXFBOPRIDOBPCXFLRTVNEU",
    HasPastExperiencedPrivacyBreach: true,
    PrivacyBreachDescription:
        "MXFXUJEOAABVBSMVIPXJFTRGDGBPJGCMFUAGLQLDSJPBJUVYSYSERXDSGYTNIOFTWOPFSGJRDUQ LFVBQAVXXKIVJRPITBRUAKVCUCJLGEQVEHQBPYGDKMOWSBQIJMCGBRKAJSGOPJRTSMQCBNRUUOK FFNOAMPKDUKHACALSTXTAKXBKOWVLRJCSEQYFMJUXLQBJCGDASEFYUUTGMEKPTYKKHNVKAGFKDV",
    ProcessHandlingBreachOfPI: "yes_not_established",
    ProcessHandlingBreachOfPIDescription:
        "MCTBBJWLLOYCNWVTLIWHEUMCVXPFFHUHYMABYFAEYGLOOQXQQETPEHQRPRECTRGDSQCBWUTFISI DEDMLQCKRLSTXKJRYOYTCNBDBYJBICVTFTHSHGFJEEOTMOVXLTMGNYVPDYKMGBCPOYOEDQJSJPO QSMLHEOLKOFLPBFYQBYWCXKYDSYSOCEWYKOAFGATCJTUGSNPVGOQDYJRHNHOFUVHJHLFMETJAFT",
    DescriptionWaysDetectingBreach:
        "TOLVYWEXSNFFOEOFFXWUGHVHJNDLFNIJPYVVVWTWEMMRHIQIMXMTTOHMRDLKTSREEVPOHRJIEYQ jjjjjjjkhom XWEJBDLUJVKWCUIMMYMBOAVPJWWAFMJOIWKFHIVEJAQPIRHHGGKEWOKXBNAEGLPVMUOEJCFDDIR",
    DoesPrivacyBreachImpactIndividualOrEmployee: true,
    PrivacyBreachImpactOnIndividualEmployeeDescription:
        "RPQPTGVXETJLSPBMJYGBJRVFTPCQSYXWINFFBGHLWJEQGNELUYBHDCLYSKVDDFFEULCFJVLCQUD BTCXFVKLUCGWTUVJNMXCSOEOBGFRQVFFIPSLYNLQDGPPPBFKDCHTOISMPMVYPRUXVBODBJJYAGX RGCXUXFACKGHWOUTUJPRUYFBCWYEPPUJTHRIMCHGUXYEFTUIBBTCSWCSBBVWYBKMOWNOWLHRCIW",
    DoesPrivacyBreachImpactInstitution: true,
    PrivacyBreachImpactInstitutionDescription:
        "JLRRJQAUWHGATRBAAGGQSXAPEHUVXBHYAUEPALRMNEOAFWIBEMFBTRYKLBMBUDVVAGYXNKANOTD NFNBLPMNJXVFMKASTRKWQFLLGOKELBSQXYFEDFWBEHRBLNFGYFQBABBITCTVEHBHFEHNEVOOTIS IHCSCKRJQMIJNNGWCGPMDUKSJCHYTNKMPCFVMPLNEUMVTMTCGAQKWTMNVIIYDROCCUSLHJKMUCH",
    HasSafeguardsOngoingBasis: true,
    SafeguardsOngoingBasisDescription:
        "UKPBMPKIMMASWKDAPMMFJAFPPIPHQNEAGFVVYPDLUXMEMIFHPKNSITXUEALEYCQYHALQNHAYJBJ IIXRTAPQJDXGOJTSBYSWYXDKHSVXMJAIYPBMCYYQOBJFHFDEHAXAQUEKEMKBEQDYCOGYIGQBACH DKJOGDWLUSBQPEQVBKEMQQIQTSSVQGRIDFHGENNGDVKENRCCOAYRCJMLBSTMKBUNASMKVKRMVXI",
    HasAssessmentForConsentRequired: true,
    AssessmentForConsentRequiredDescription:
        "HNTRGQBGJHHJKGONSWWBWLEJPHPUYPUTGWIGKCBKJIJDGBFUVUDSJVJUJJBYAFGTMNDMXHCPVLQ KAPWQVJJMDMWYFNPWGCYFVFJSBIQWGFVMBWWDFMPMGYGLAKKRNEEDFCOTGEONRLGXPJXHQLQSML ULWAKSIWCIAAPOVYBSUJUNRKKTMVGQPHLCQJLKMWRRTXMVJFRSSEOCUGSLOPGLQLSROMXMNPGXQ",
    DoesSeekConsentToCollectPersonalInfo: true,
    SeekConsentToCollectPersonalInfoDescription:
        "XMPVUNRNVCDMQYPHAICYALBMYNCGHQKLWGGKTXEWLCDVAQDSLXDFNNILKDVGKLFEQROKSFNBDEN DXULQUHGXKIUDYBJHBEMLFIDSAXSERETJSYIYYNITUFXWUWSYQRKHRSWPRSPVOCGGNKJYSJIMUS VYHFGRVAOFYFTFFMFTCUPKCRLPNXBJVLXQGMRCVWDDCFOKXRKXAVCVPLVOTQEWYFJNGCYRUCXFR",
    DoesSeekConsentToUsePersonalInfo: true,
    SeekConsentToUsePersonalInfoDescription:
        "UVTAPXGMQWMFVLRPPSXUKCIVSHWVSVHUGRJIIIATJQDSXJWVVBTUDAVSMWHHAJSUPRXECIGGRDK IQHVUITPLEAYFWJHBIMHIHJDCYFCSASFRCHDFMJGYDHBVYPPGCUKMCBAHETVDRVLLUGCPGCOYGH PMBPVFKYWMMKATPQWCDUSYIRGIDKWMCJTHXGGHJIYERXWSGKGMFLRBEPDIJMBABKJCPSVIKPRTU",
    DoesSeekConsentToDisclosePersonalInfo: true,
    SeekConsentToDisclosePersonalInfoDescription:
        "BOBHHTFRLHEADTMACULEGLLCJSGPBVNVUIGMHGVQAMIUCDNWGASWUKJPCXXOMOQOTHETNYRUXUE XGSLEXFQYRRDQEUNXBRHYPEPEBRIBUXAMSJYJHIRWHQHUYVVMHHQGGQIBDGCFVPETQPWUUDQSYJ RMGCUYMWKKNFLINXBICQGOBIJCFRIUKJNMXKHONMWAMOBBONEFSMNXCCKWRSTTNOYDRXJDQLTPT",
    InformationConveyedAffectedIndividuals:
        "STNBMEDEJXGRLCGOLUUOOSTOTJSDQDISKGLHMTXJBXUGBUCNBJIAVJHYYXGCKAMFPMHFQXBRWKN HAKODHPAVQPIMAASXKPUXLNVUXBAWXVTNAQXOBMFELDNFWLDKXNXPQDVLOTEFPCWUVTMJCDVWKQ SIOJKWTGPATGSFLIUCQMKDUUXYTCOPFMDFAKJYCRBHHHUGYRSHCKBNFPNTKLCRQATGDMEAXUAYK",
    HasPIASummaryOnWebsite: true,
    PIASummaryOnWebsite:
        "DRUPLNDDDVHXDUAYQCBFVTGXXWQHEXETGYOQCERXGGCUONRMAGOPBVNILVQOWUXEQMQEGIVMKCX UBGWWLLCRFIMPXGDHHHLFNWVNSFWMGLIDNYTUWMCGPVAJOYIXPUEHNVHDJIDFNPLTYIBYLHJUFE DPWENNJBGQRFYYDGYSAFFLRKNEROXCYLLRPMMBOLOMGGLOXKPBHGBOKRXMPJVTCEQGTGIPSWENP",
    BehalfMultipleInstitutionOthers: [
        {
            BehalfMultipleInstitutionOther: "",
            OtherInstitutionHeadFullname: "VTVTURWGMYCEWPTYAKALBWCKY",
            OtherInstitutionHeadTitle: "NENBAVWYRSDOVHMOMLYWKDCVG",
            OtherInstitutionSection: "LMNBGHIETTQPMDWHVSKQKOCTN",
            OtherInstitutionEmail: "YMMCDGWTMP@gmail.com",
            SeniorOfficialOtherFullname: "KQDFVRVHLMANVUUSQJGDWMGYL",
            SeniorOfficialOtherTitle: "LWNIBANHXSIVIYIFLLYPQLGAD",
            SeniorOfficialOtherSection: "HDCAOEUGVIWYRLXPMIGDHTJCX",
            SeniorOfficialOtherEmail: "OODIBTLLHS@gmail.com"
        }
    ],
    DocumentationRelevantISALinks: [
        {
            Link: "http://IXKDQWVCFR.com"
        }
    ],
    OtherPartiesSharePersonalInformation: [
        {
            Party: "ERVQJFKUIFIYCXAKOLSAWBDYM",
            PurposeOfDisclosure:
                "XKQEGPQEFRCXGOHJGBJXGARRTDFYTKMKNNMSPVBUPHNHYEHCHCYRHVMXSYJDJRKUEQKRBOSJYOH JLBQMWSHSWJCAPTVXOWQUREDSNGUFBTFREWPQVEJBPQCIMCXAAYRPOKQGXWXPWCRDEKVRDFBKMO FWSRJILDDRDQXRQMDKNDJQWEYVUGWYDGROJGIYBBJCHDNKXNLOJWQCBNAORMMEFDNVXIHJDDILS"
        },
        {
            Party: "green party",
            PurposeOfDisclosure:
                "XKQEGPQEFRCXGOHJGBJXGARRTDFYTKMKNNMSPVBUPHNHYEHCHCYRHVMXSYJDJRKUEQKRBOSJYOH FWSRJILDDRDQXRQMDKNDJQWEYVUGWYDGROJGIYBBJCHDNKXNLOJWQCBNAORMMEFDNVXIHJDDILS"
        }
    ],
    PartiesSharePersonalInformation: [
        {
            Party: "other",
            Description:
                "HVUCMUUDSVHSKUNPTSRQNEJDMERDHVHCVVNVLWYGHLCUCQAYYJRKSCJCMQPICRVVNFVOGREWSLJ FOPRBEBBTBVXADKVPXEMWTCVHKEJNCUAWLAUTMLVMCFKLWBNECCRUNBLMSJQARNQFVANCOBCMHA BMWFJTIIBNUGYMCKWXMEHIYBFXRLATMKDYPDHLDACPCCDFVSBAOSVGUSMVYKBVHGAJDAWYCLTLC",
            RelevantISASourceType: "link",
            ISAFilesParties: [],
            RelevantISALinks: [],
            DocumentationISAMissingExplanation:
                "TEFDTIXQXSJATYSNGFTTPIJSWIUAUEHMCUXBRHLBITUNKRMGXPCBFITLTLGLNXVSLWWXBRUXSRK LJEWRYLQNWIJUTVRDDTFCQAEPQAKYAFVCNQSYMOLCBTGSKWGFMTEHYFTIYHBXBRMRLGGCDSQNHD LDDAMXWPUEWCLFYCDSQMLCWKTDWVTVKKBOGKTPHYGJBSYTKCFSXGOOKIGRGJABVYSMAVXOINLRF",
            AreasGroupsIndividualsAccess:
                "WDMISVDOFSXYGROAAVUOYVYSDXVWDSVDUSKXJWCETTOQIBCNIRCSCJQADTFUYGKLWTENHQQCTPT OFTKAHJAYBCUMCENGNXECRTPGWEHGVASHBSKGHOUNRHONXHHJHAXUKVVKEDCCBTCBINKITGXYCP TCLGWLNXWJLQMBQJJRMGVPSHEBJAPKIQJARYHQTTJNRLEFTIHUCBRCDDIDBUCMHLBUHMJRBRXSW",
            WaysToProtectPIAgainstLossOrTheft:
                "BACFDRJATLIMDKRQEMISVQKTYYNREJYHIFUYBEHTKOKONKKRENOBKJNKOIGEERVKMBEXOSOAFNI BJKQOUIBLHSWTWGROWRVRKJPEGSTTCDBTWGMJQTHEQUAGWWLPKFGDGDQAULHBOHIEQDVQTIXDKR HKEBNXEHBCIJDGLYFYSEJTSSRMQHSCVWAQIJYBIRJXWICLWPNQJNBKUNQLIBGVNYGKJLXCADQAU",
            MonitorAccessDescription:
                "WXJBKTQKGSHKCFNPOBLBXERLKVANUSLBFUVVVWXSQYEAHYKRCEIGAFPRGXQNSDPNHGEHJRTQCSJ BTIPBUJNMMJWFMWQFECRJAOVXVQFRPUERWOXYMSWLHGJOBKOJCKSQHFBELQEEEUVRFFHXXQRKEF VDYKHPYSOKVQKHJRILMRCBJFIPKICQIBJOKNORNXYHHHXYHPBUKGKJPTTTCQEQQWCUGUVUCPXNR"
        }
    ],
    PersonalInformationCategory: [
        {
            Category: "from_social_media",
            SupplementaryInformation:
                "MTKWMIBPWVEUYDLQPSOGJWBLBWFBPHAPWNQFGETUFOPGQEQVXBYCPMGPRXVPCYAPUNXLLGKKXTB FDMHUUHQYXYAERJEHGAMORDHYTXJAKUPONCLTLLCHJOLLARWJBDNLIUNAEHBWXPNCJKQOWKUUXF JWJOTUVYYLKTJRRXPRWDCAHDAGKQLRIHOFPBJJBWQSBGVQOMHWOSQWXIOGNNJEMGCDEEBPOFQAL",
            PersonalInformationElement:
                "NGRSLODFORWHANMPWESBWHFVSIVASEGUVGHWPJQFNWADOEJNWATOHWGFAVYCRDLJKCKSGOYMNNN DVVMGPJPUFPHDPMUNAHFXJVJNMHGWXCDXDFTSAVRNUAPWLGBTKUINNLTALYSICRWDMIYKSBMEPQ UIKRBULEECWXLQQWJELGKDJKGUOWLSEWLCTVVHECESMXFEWCBRPSILDQYALGGNSLXAMIWTACYIB",
            PurposeOfDisclosure:
                "EOPNAKNSXLLGCSTAJYBOKFWKFQNGPCSMDNNIRHPDRQCQSWKWBRGHQEHXREHJWGCVSYDOELHBIXV MDVWPMNVYVSKUDTDIBTHTDVPJPMTQEBVWEIUSEFYQNMYHOTJMIABWEVIHFNYYSFTUWMPUXJDUTQ FERBEUHYMPWEJABVPDQAMCDHDAIHQJPFPVAVKJEFAVFVSCRNXLFCVGIDAKWELAIDARONAFLGXLY",
            ReceivingParties: ""
        }
    ],
    PNSStatement: [
        {
            Description:
                "XSSXCIKDXVTFTBFUNUDETEDJEXIVGEOUCPYRJYHFJAVKIDBUKBPXDMASPITDYOWTHYCDCMKNNWU YEAAUMEHMTUXABWRIRTLHQRKXFNUSWKMKOXOWGCTLIFNDBIETLCDPISIMPCOXINPIIMKDIUCPYY TRRWBTNNWTYLTQYEGSELYEHMNGQBNAGQXVFATLIGEDLJTVNGWXUUOAJOKEIUDLYWNHMXLXJUJXH"
        }
    ],
    SecurityAssessment: [
        {
            Title: "OPFUPATKIGKSGAKRVDGCQACBQ",
            CompleteState: "yes_not_completed",
            SummaryType: "enter_text",
            Summary:
                "ARLYMJPCNUEKMHUWRHBSAORQKFEARDYWYPGJJEBCJIVBMXUJBBTAXKMKATNHEOKJVHKWAKMNFXJ GRIPFNOWYNLRFMDFMTRIUUEWLVMDSVDOELJMAJMQORGOLITYFTKNCBVLMLDIBLDDJVNTCQECHBS CHEGNHMMVSXARUQKEAFMANONPFQNKDPOKUVWXDGUMRCEVUPKJAMDTIFNRQQIPXCSDIOWXTLBTKY",
            SummaryFiles: []
        }
    ]
};
