export const piaTestDataOld = {
    AnotherContactEmail: "anothercontact@gmail.com",
    AnotherContactFullname: "Another full name",
    AnotherContactSection: "Another section",
    AnotherContactTitle: "Another title",
    AnticipatedEndDate: "bvcbcvbcvbcvb",
    AnticipatedStartDate: "vxzcvxzcvxcv",
    AssessProportionalityExplanation: "hfgdhfgdh",
    AwarenessActivities: "fdgdsfggdsgfdfg",
    BehalfMultipleInstitutionLead: "1",
    BehalfMultipleInstitutionOthers: [
        {
            "OtherInstitutionHeadFullname": "Hugo Roule",
            "OtherInstitutionEmail": "yougo@hotmail.com",
            "OtherInstitutionHeadTitle": "Rouleur",
            "BehalfMultipleInstitutionOther": "2",
            "OtherInstitutionSection": "Astana",
            "SeniorOfficialOtherFullname": "Julian Alapolak",
            "SeniorOfficialOtherTitle": "Puncheur",
            "SeniorOfficialOtherSection": "QuickStep",
            "SeniorOfficialOtherEmail": "juju@hotmail.com"
        },
        {
            "OtherInstitutionHeadTitle": "leader",
            "OtherInstitutionSection": "Astana",
            "BehalfMultipleInstitutionOther": "Mental Institution",
            "OtherInstitutionHeadFullname": "Lopez A",
            "OtherInstitutionEmail": "lopez@gmail.com",
            "SeniorOfficialOtherFullname": "Tadej Pogachar",
            "SeniorOfficialOtherTitle": "Sprinteur",
            "SeniorOfficialOtherSection": "UAE",
            "SeniorOfficialOtherEmail": "tadeg@mymail.ca"
        }
    ],
    BehalfSingleInstitution: "2",
    BehalfSingleInstitutionOther: "Another institution",
    ChangesToBusinessRequirements: "dasdsdsadsfdsf",
    ContactATIPQ16: "conduct_pia",
    ContactATIPQ18: "conduct_pia",
    ContactATIPQ110: "conduct_pia",
    ContactATIPQ317: "conduct_pia",
    DescriptionConsiderLessIntrusiveSolution: "fsdfsdfsdf",
    DetailsPreviousSubmission: "this is a bunch of details about the previous submission",
    DidConsiderLessIntrusiveSolution: false,
    DoesHavePoliciesProcedures: true,
    DoesMeasureEffectiveness: true,
    DoesRequireModificationToIT: true,
    DoesStaffReceivedTraining: false,
    DurationOptions: "one_time",
    HasDataMinimization: "not_yet_planned",
    HasLeadInstitutionConsultedOther: "no",
    HasLegalAuthority: true,
    HaschangesToBusinessRequirements: true,
    HeadYourInstitutionEmail: "jack@gmail.com",
    HeadYourInstitutionFullname: "Jack Travis",
    HeadYourInstitutionSection: "My section",
    HeadYourInstitutionTitle: "Boss",
    HowMeasureEffectiveness: "",
    InvolveNewSoftwareDescription: "bvcbnnnvbcnvbcn",
    IsAnticipatedEndDate: true,
    IsAnticipatedStartDate: true,
    IsContextualSensitivities: true,
    IsHeadYourInstitutionResponsibleWithPA: true,
    IsInvolveNewSoftware: true,
    IsNewprogram: false,
    IsProgamContractedOut: false,
    IsProgramInvolvePersonalInformation: true,
    IsProgramRolledOutPhases: true,
    IsThereCollectNotIntended: true,
    IsTreasuryBoardApproval: true,
    LeadInstitutionConsultedOther: "glkdsjfgkljgk  jfsksjdf",
    LeadInstitutionHasNotConsultedOtherReason: "hfgdhfdgh",
    ListPoliciesAndProcedures: "fghdfgh",
    NewOrUpdatedPIA: "new_pia",
    NewPIAAllReferenceNumbersAssigned: "V13R5t9O",
    NewPIANumberAssigned: "new_pia_existing_reference_number",
    NotInScopePia: "jkhjgkhjkhjk",
    OtherInitiatives: true,
    OtherInitiativesDescription: "czxcZXC",
    ParticipationOptions: "participation_mandatory_and_automatic",
    PersonalInformationCategory: [
        {
            Category: "address",
            "SupplementaryInformation": "gf;lkdsjgslkdfjgkldjfgjdklfgjdfg",
            "PersonalInformationElement": "Rouleur"
        },
        {
            "Category": "d_o_b",
            "SupplementaryInformation": "yougogdfsgldfkg gldksfjgdfggdfgsdfgom",
            "PersonalInformationElement": "Rouleur"
        },
        {
            "Category": "ethnic_origin",
            "SupplementaryInformation": "gouirtghuthguhtuhg",
            "PersonalInformationElement": "Rouleur"
        }
    ],
    PersonContact: "another",
    PersonalInfoUsedFor: "non_admin_purpose",
    ProcessHandlingPrivacyComplaint: "yes_in_place",
    ProcessHandlingPrivacyComplaintDescription: "hfghfgh",
    ProgamHasMajorChanges: true,
    ProgramName: "ze programme",
    ProgramOverview: "cxzcZXCzxc",
    RelatedPIADescription: "related descriptiohjfj",
    RelatedPIANameInstitution: "related instituion",
    RelatedPIANameProgram: "related program namexxxxx",
    RelevantLegislationPolicies: "jgfjg",
    RequireModificationToITDescription: "gsdgfsfdgsfg",
    ResponsibleComplianceWithPA: "hfghghfgh",
    ScopeOtherPhases: "gfhgfhfghgh",
    ScopeThisPhase: "fdsafsdf",
    SeniorOfficialEmail: "adam@yates.com",
    SeniorOfficialFullname: "adam yates",
    SeniorOfficialSection: "michelton",
    SeniorOfficialTitle: "rider",
    SingleOrMultiInstitutionPIA: "multi",
    StaffReceivedTrainingDescription: "",
    SubjectOfPIA: "other",
    UpdatePIAAllReferenceNumbersAssigned: "A3Rt67U8",
    UpdatePIANumberAssigned: "update_pia_existing_reference_number",
    UserEmailAddress: "test@gmail.com",
    WhyNotConsiderLessIntrusiveSolution: "hfghfgh",
    WhyNotMeasureEffectiveness: "hfghfhfhfghfg",
    WhyProgramNecessary: "fdsfsdfd",
    WillITLegacySystemRetained: true
};

export const piaTestData = {
    HasLegalAuthority: true,
    RelevantLegislationPolicies:
        "SUVVCQNXCEECGALJWEHVFQUMMYOYYVIRGPJEAHWWIDTQEPWGRGKDSWXCYIICCNYGUMUPQGIPHJM PVOFBEKFNQAYGWJOQSBMAFNHFDOEJNRRYFNSTMMUIROKVHBHMJUNXPGJHHYWOGUAYIABIPUEGGD JCGQRGTQYJCMQGGRGQELVTUIHYMKXGMURWMNGKAGSTNUDFXPLGWKEHROHWISTJRRVGTTTSKVQXR",
    ProgramName: "UULJPJTHVCRIFTPONJLXAPUXV",
    IsNewprogram: true,
    ProgamHasMajorChanges: true,
    IsProgamContractedOut: true,
    IsProgramInvolvePersonalInformation: true,
    ContactATIPQ16: "no_email",
    UserEmailAddress16: "THPUIIKCUL@gmail.com",
    PersonalInfoUsedFor: "admin_purpose",
    ContactATIPQ18: "receive_email",
    UserEmailAddress18: "AHRLQKAWFS@gmail.com",
    SubjectOfPIA: "program_activity",
    ContactATIPQ110: "no_email",
    UserEmailAddress110: "RHKRNFDMLM@gmail.com",
    SingleOrMultiInstitutionPIA: "single",
    RelatedPIANameInstitution: "YMHSAIQOYTDYLYSODUQUCJWPS",
    RelatedPIANameProgram: "FNYYPGNBPAMAOEKIMPJHTKBEU",
    RelatedPIADescription: "FWPKWKKLVYUKHXHHTINSOGPBL",
    BehalfSingleInstitution: "1",
    BehalfSingleInstitutionOther: "SUUGGMJDHWIIVRWQQCCTLJMMW",
    BehalfMultipleInstitutionLead: "",
    BehalfMultipleInstitutionLeadOther: "EXOGBVHAGNDEABBRJRUAQJHTX",
    HasLeadInstitutionConsultedOther: "yes",
    LeadInstitutionHasNotConsultedOtherReason:
        "XJIOPAMHGHIHHDAULKNFGFKRJIUVUIIWAQNXNGWNVVVOEKTKVJGANAQSYQFHFQLXYLHPPCGEMAI KJYJNYMKECSGKFXVGDGASESKNFCMXDBXQRHMUBOWUQAETRBIHWCVWWRGQOVHWALBATORXLBENJE RPRPKKFXUMFGXSITHYGLUQRCRIBXCCJFSOSRRKIORGKSUHTIAIKCEYRBWPWCIGVRDAMIYQBVQQS",
    IsTreasuryBoardApproval: true,
    HeadYourInstitutionFullname: "DQLLWLEHUDQAPVWDIVYHADJJQ",
    HeadYourInstitutionTitle: "XGHUGVJDQFVVSQUJAPQWSKVEP",
    HeadYourInstitutionSection: "FTXSLDSAUWCICWHVQBPCEQBHA",
    HeadYourInstitutionEmail: "EXTYIJTGST@gmail.com",
    SeniorOfficialFullname: "PPKIUTKELYKRAVBNQAANJDEYG",
    SeniorOfficialTitle: "HUEUQVYGKLAYPRVPVYUEIRIKI",
    SeniorOfficialSection: "OGYQWKHOGUDXNQEQQINDODJNG",
    SeniorOfficialEmail: "YVCITWBISS@gmail.com",
    PersonContact: "PPKIUTKELYKRAVBNQAANJDEYG",
    AnotherContactFullname: "GJUITGEGSWISQHTIVCLXCUPJG",
    AnotherContactTitle: "LKYHWUCNUODWACJMYAKLUBHXW",
    AnotherContactSection: "BQDTERYQFKFQARSKOQOKSCWON",
    AnotherContactEmail: "MLPFUQLADS@gmail.com",
    NewOrUpdatedPIA: "update_pia",
    UpdatePIANumberAssigned: "update_pia_existing_reference_number",
    UpdatePIAAllReferenceNumbersAssigned: "YCAEAHEERPCAUFGFVNQNHASQR",
    DetailsPreviousSubmission:
        "WNRCDVTURMUCVUBCSPSLXQJFDXQFOTSXQTHWUHAGKOQHJGCQNYXWLSVFELXFENFXSWKBMEGKOMA FCHMCPAYYPEUQVFFRCXPEOYCVEVTDDFRNQPSRAKOEQHAKTESBTPGRXWQCFPXSFUUJLGAGMMQQIL JDUJGNUTXVNFFUPWJOTASYGTFMLGCVUOAHIHWMSJGMRQWBGMEGDXDQAJWADSCOQBBXEWMHAVVJS",
    NewPIANumberAssigned: "new_pia_existing_reference_number",
    NewPIAAllReferenceNumbersAssigned: "LVEQLFFCSIMWDYXXISAGVUTCE",
    ProgramOverview:
        "IAREMDFCMQAPJYIBYASKNAQMIQNUIVPQQWBFELEEUYGLPNJHEILBWTKIJEVVOKSPAIYLWDWNVOP JDUXFEAJBIXLVVJLKAVVPAOLFHLILWTEUBSCJARAGCXWDRDJXRBKRECJOJSWSQXENSPUDGBKHUO QSJNMEPUYDXLRTUWAHWGOMBAAKGTQYJCGHGUBCYIDDSSEUFHQILMNMODRINCXVDASVEJMYVXHNC",
    ParticipationOptions: "participation_mandatory_and_automatic",
    OtherInitiatives: true,
    OtherInitiativesDescription:
        "CVGTRLRVLSRKWFCDGJOFLPDXLHQXVNMPXUKLVPJWNXKTEVHQWORFQRVLRHIKUTAXGCMBTPHPAQR XVWTDXRWFCAVQUQDLVNWVUNCBKEWXFSJSNGXNEULOARRJVGPLBXYMMOCITRSTTYYIPCDOROHBCI PBFTHYHAEGYLJDRJOAQESEPPQEEKFGABLIJDSTCNEFXOBLKHGRDTNVYLKOCDTVTWFWYBSNPTXCA",
    DurationOptions: "one_time",
    DurationOptionsDescriptions:
        "CPNEOKCTRNXNERFCGJAPKCRJOPMGKKMVBNCGXQMISNFRVGEHWTXVHYNAWDPXXVIGABLPOYEOWQV VWDKGFGPKQXMOYPKWJUIQKGRCKUCAEPVAUTYFAOXFSTOWNDDCWVKOCNLQKIUJEOFBCLSFQFVTWD FUGMSCKKSURDBBMAFBFSRWDIAIUAYOLEACLVYRXILCBOIUYNCJBIKMKIQWLKHJLDINDXOPANDWH",
    IsProgramRolledOutPhases: true,
    IsAnticipatedStartDate: true,
    AnticipatedStartDate:
        "IQAMMMLFWARSMELAXYSMMDPTXASXFFELNAPLAJWDIIWOVLDOPBYTTVVEAFOMTMARUFELNYANBOE FVLMUKNICPGWLKJSTUYTPCBBQENCKUVDALOYSNFJQGHJEPDRJVTHGTRDUJUPVKXHSCVAVJAFPPC TAWUVUFLHXFIYSCPLESSGVCKMELSKUEWUAGGIFWHEPMEGCLIVDJTEJKXXLHRJMALTIMXMVHFHLO",
    IsAnticipatedEndDate: true,
    AnticipatedEndDate:
        "EYWHJGEJRUQLHMLLFVSMUYDXGCXBXEEPPCBDMLNWSINLKYMYAADIKDCFVXBGHCKMPBVFKHXSIVS DQSJQYIXHKNCNBLICBEVXFXEIHWHLPIGBLMULEBMVFCHCXGHVGSFCOTWRNAIBAMRCGBCNQWXARA HVIEJUYSAMVLSIISSHNDQUSQOXNDVPRVRUXKDOHADWYGKAUQNYCIYRBMDQPKGUWKTATXKWPEAMY",
    IsInvolveNewSoftware: true,
    InvolveNewSoftwareDescription:
        "NJTWLEGFPUMWKDEKXUQDNIALIPJJPJHFLUPWKIMKGMPGEPQHGJURTCSFIHNUUWPGNHLOMHAPHFW WMYBSCXJHSFASEKCDJXWBJNHLLCIWIASJBPCJLWINTSQSEUCVAPTHEENXROHAOLYSLQROHSQMOI GKGFURAXLDRRSHWKENSFMYGHUTXLDKCXCHJALJDUDDQMRWBQMATRFXLGEYJASOUBBSPLXWXUKXB",
    DoesRequireModificationToIT: true,
    RequireModificationToITDescription:
        "HISLSYADIPPBXPISFPTWTVWLJRRSVSHRYOMOGQEQIXEEHIJICOPJVTPLKHCBHGGOIXBICSLNLCO THJQCCVYKHFIJQYTCMKBRDBAKOFNGVACUKJUCVKHOBFIVLYAFHCRULOQFIFMVHROGDMYGERFCCL EHJGLAVYQCPACIXLIKMIQQYUWKURWKLVFBOLMFHPKQOJPVNTIBYOLHMNINJBEECFQSTBSMYCCWW",
    HaschangesToBusinessRequirements: true,
    ChangesToBusinessRequirements:
        "XRLJAKJSRJIVSKCIAAWOFHKJYJDXHKEJTFGKJIGDUWIGAIIOILITRWWQHBJPHLKGEYCMERYQTTT ILAMNBBHEIJEXGWOPMVIEVFRKFKBBROQFOMHKYFEVRDBOAGSVEITTWFMFICIQYGLSRYJSODPGQM KVVKMLAWXTXEFLCILHWRFSLFIAHXXNWFSKHIKARXUYUMWVOHWQTAXXVQKQCLEBYJVRLUETWLPXV",
    WillITLegacySystemRetained: true,
    AwarenessActivities:
        "UQQVVJHSHRGSHXTURRLMGBXNWAMRFGXWFLIWBKTQAKJTPVHPKDBWTATTSDXUVPMASIMUOWSHXUM YOEFRDMMVJKPSLNPQPKHDHJCXUSMDIXDELGCNRYIMLSEMUJYMGSHKOUQFCHVKYIMLHLGELBXPBU XPITCRDSDQYWCEADTUONCCVLLXEPKRUWILRSAVVTQRUGLPEPVIGWXESVSWIENNHLVCNQLHCWXTV",
    ScopeThisPhase:
        "OBWSIFMSOQURPIUPTMAQIODHLTJHOHNEMWNKNISTJJGPDUEKIWSIHCDAXOGNUEEHCPFRTJCLSGG QRBIEUEMGEGUYQUNNPORHQHRTXDPXAWEWLHAWIRILJJGQSKFCQSRQDOAJINGQOOFHBWNJTPEWFF LCCOOUHHKFMCHAYFUIVEYMWPPXVAEHUOHDJAHQLOPFAVQNDLNMYIQLLYFLYQXHCCKWUEPXWDVHN",
    ScopeOtherPhases:
        "DFBNRRYIPMNUFHYHHNHFPSKXXSVCKACFYFFSTQIAGWWUCGBOYWDGABCJUCPYVWXPKHUABFMQEHX QHOGHIESKBNUWSYYTJXAREXHBJFIHGAPACKOCWJFFCVBVRGRCFNXNYDMIGEXCVLEAWTUHKVWARU CJUYDUWHHDMCEFYSEYEICMAQBELUGIXAJRHGOJMJJYGNDNRMYFISWRLPIDWXJBAXFMRMWSEULUX",
    NotInScopePia:
        "MJKBWUBISBAAJLMSTVTTGYUXEUADBPCTDBAAXTWUIQJODEBVUCLECGLNNLWBUWGDXFWILMTYXYK AIRUXFQTQIFVQJYMVILYYSUEHHFRWVDJYCAKUWQITVXHRBCYGCNDSESGNMMQAXVUEUWOJNRXQDF ROWHPYXXMYNLJTQCYMNFBOUYKWGUAJRBHQNYAMDIVNHSKMNKBEWOXSUDTWWSSCXCHLESFRBMJFI",
    ScopePia:
        "UXHTULYVGHVMGQXJBQAMQWBISQAWRQDPBPHUHTPWPTFETBIVIEBBSWEWVXADLCDODFLPJCCGADW KOHCVKPSGDSIAMJKADCYIEPWVEWRORUHMJDYNXNEXWHRAFHTJDESIPUFXJFQNXDOIKUQIJVCOXA KOSPNLOQGMIXVADGEYVHKJSUKVDLRKGMSDTJGEKHSFBTNNUOVSCFCBKAVWFRHDXUGVFRGSAYONN",
    NotInScope:
        "RJBROUVXIEYVDRWDKWNMLVAAELUKDXIAWVLRQYKCGOLYKNHTBMKJTBXVJANCYLTKUYYGGEMKLLF PAISKAVABMCKWNWMNUHTLSHVUFBPXWSCPWXLKOGQYNHAGINQWITABOKVRLWEYGCDSATYPKBXNPU DHLMRPTCHMRRSTDYVSIWGGJRVJSDKQFXTIAOTJVNRSFNNQJMAVTUFHJVXTQIVQRQHSXJTNELVTF",
    WhyProgramNecessary:
        "XKLJJGPOABSFOMWMPYVAWYDPOARAOEPSQHGJKWXWOTEKYXOPFCXIFFBXHVTIOOAVKAOHGMCSAYK LUWUVTLVHQVKDYGKNRNFBTGUHJQTXDUPFRJGUJVCUYJTDXXVKOXOYSARNBNMDQWEVGELPAOEULK YKXGFTUCAJHRAYKPMCOQNWQQFFJJXRPJPTTMCDGRQRXAGUNFVTXCBGABTHBAKKEHSWCGFXMJUWA",
    DoesMeasureEffectiveness: true,
    HowMeasureEffectiveness:
        "UKGFSGWFIQGVMGUFRWUFFEVSRMSMJDQWCBJPXFVSFHJOOQOATFIXJUJQONMFMKVEAISKVFHLABA NPLNXYRBAJAWUEJIJCODLUMEAIFITOVETRXUIVMHQSWQRKFCCNJKEPJRCGNOTIHLNVDCFOYMPGL OHBJOWSRJLVJWPTWPMDAEQTNAHMRDSNBWSUDHMFPWJXJCMHVTNAQVVRXMNIGJAOQXUMEUQODGNC",
    WhyNotMeasureEffectiveness:
        "HMDLYPSNQHGCSXSJWHWPBRPOGNBTHFFNGYAFSDCETJUIWAPLDFFGCNAPVNFLNXFKBRUTXMPSFSV KNHDVYQFIBXIWFAUPGXULCXQFBKCBVDXJUPPICFDLVTBDXWVXPFGOIJIPQXTNODLXAYBOKMNAUI ELOVSYTVOJPQCCEUCEMKNKRNLPHOTPYHXGJXNKEYGLBHCQTVLLXWKYBSTBKDRFCYKHRVSFGRAME",
    AssessProportionalityExplanation:
        "AJOXNTIWDFSROMCDQHUKSESMAVWRJCNQNDFRIACPLFMUEVIBQWDMNAMUQBXQWPMBRBELGJUPEFX WIFSWTCKJYDHUUOGYDWRVUVRMFATVHCNGYQVMGSXHBFMJGCFJNTXRDHCMNGRSINCVPBVESSRJYJ HOCCPOGNBPCSPTIHTMARPSOMPOFXPCTACLIEDYCUSPEJQWSSCGTCRUAOYOLBJHWYUBQDLEEUKEY",
    DidConsiderLessIntrusiveSolution: true,
    DescriptionConsiderLessIntrusiveSolution:
        "XQFFXSAVJMPWJYKAXPBVTFOQAKOHCNMTVYTKWETJIDLTKQXBTVLNVIUSBOFNDSSVYVAJFYCTVQM KVQSRIENGBWCOUROWGQYDBPQRNBNWPJEUBQERDBEVXMTAHFDMBNKLCWJFYADGPPQQRGMDNVSELD PJNBQENQCCTPBURGTCOENXAROOKVJGDXMQJJQDIBLUXJECVKYIWEBRNRIVLBSQHVXVCKKIPQSMR",
    WhyNotConsiderLessIntrusiveSolution:
        "KTDWKNOJMGBRHFXVQBIVBSRSUTHRLBTUMJTVLYAWFQRNFTBVDDIXIFEQCJCPGWWLMFEWKCKQBLP UAYMMCHPWRBOYJVJPETSKPPPVWOWGAYWUBNUMDJTBHKFRTGLEDGUIYYFKJPPNJIVRDSXUAVMTYQ JHTCUKRYHDUIGDDTSJXEKRGNKVJOPYGJPVSUFKLEEMIQMLJTWQTFSTJRAFQXACIHVLRKJINIXTA",
    ContactATIPQ317: "receive_email",
    UserEmailAddress317: "GJKALTMLBD@gmail.com",
    IsHeadYourInstitutionResponsibleWithPA: true,
    ResponsibleComplianceWithPA:
        "WAVPGXYNDTYDFUUXFSWYDPXAAAPDQGXCKIDRICFNGBMODOBIEKMLOKDHCVPGIUWWVVRVQCODMJR MNXLIVAOHVMMJMMUHRAWOGGSCWWRIJUBYYSPRJURIOEYOBENRCMRJMEFHEJLYHGXALMKTWDWWIN WGSNAIJHGTLJWJLTLKCPRFFVRUUNIHGRVUBMFDWCODDAQAJKTJFFJHXQBVUFNUXYMSMCHYNINAA",
    ListPoliciesAndProcedures:
        "GJQTRPGBQUYNEEIUVKSBSSCTHIFLQPAXHHUDQAECYVOOFSELKWRBHGSMGVLJJTJAUAFVJFDUGPB KLVJXNFPYCARKYCWDFFSYFBUDMXOROKISIOSTFSVHIJWBICHADLSVEDEJBGKPPWKQQXCJICWLIL KLGTQYALWAXWNMXTGAPAJVIATTVOKQGGTARWOBYAWJGEEPTOICCWXIUOCFYVDKAGTQDMUAEFBOD",
    DoesStaffReceivedTraining: true,
    StaffReceivedTrainingDescription:
        "UCTDWHOPPJPRMDLVDSKFTHCASNPHCVJHJIDDQQRCOCGGIRMTSKPUYWFNATJJRHNTYHHEAHFLAHP ICEKXJXFMTPLYBPROUQFKCWRVOFYJHEFRDAFDLMQTBTTWIPSPYPLPLKFFMNIEXUFOJTVAKODHAL LGGRVGEUIUXVUXGBTDHXRGYDHMGELTIBREYUDWFMDKMIHJQWCKEIPRSFHCJIYAIOMWEPXKXVXUU",
    ProcessHandlingPrivacyComplaint: "yes_in_place",
    ProcessHandlingPrivacyComplaintDescription:
        "OQHDLTISFWPFNSTEWOOFXLNMCLSRYCAWQDFKGOBLWPSABDONULCESIGCDUBABPSCWSOJMIXHMCI HTLHJSBQXRXQKJKPQSWSDUWLVSUAGWDDJRRPQBCNOBULUPKAEHPSSEWMWYLQXAJBOTGSRTXPPJD WBTMWPXKICKJDOBHKRTOBFSEHWCPWALLMMCCQQMPDFAOMWTUMESKJIJQHPEYMHMIPYWPLYQTFEK",
    HasDataMinimization: "not_yet_planned",
    DataMinimizationDetails:
        "SCSNVRQPQPWCTJEVGBSWDDGUDVJOHISCKWPUYUQERUHDYEBKGOUDCEAOUXKYICHHVUQVTJVKKNE PLXFWVMVVXUGKSOEXTAKXWXXUIRYQQXMHVTTQYRBNKVNIVQJOUUWJRJRMYKNDNFEAHXNYTNXCXW DGRRLGCFXQXXUXQSUEYIMQTPUIUGNXLHKPEPIGSEQAYSOVINECGQMEALLCWDKVRYEPNFTBJOLTQ",
    DataMinimizationPlannedDetails:
        "SBEFHQHXWHGIKDXPVTIPURBUWARVJEMLJKOAENFVHVCLXYBBTDERAROAYIHGYKNSUUXANWLINLH DTNGYRRVTHSEOTCHDMMMMIUXPYLVXVHKRTXBGFUYIKXTREMINXTOVLPUXOPYGUXXAHMUUBBWQMD CDAYSJHMTLKYVAEGAHCUSHBXDDPOVALHSSNISSYDGBYEGXEFFAQYRUFUBBVOTRPSACGCLVMGIYO",
    IsContextualSensitivities: true,
    ContextualSensitivitiesDetails:
        "AJNUNDQQWQVCMVBGSEUIBSMSWTGFUDMCMXEXUOANCROOEPWKHWWUUBIGWTWTWLVTDSOORCLEEGF YYMSNJKSWJPXSWTSTIHERKJCGJQEJFXRUQHEPPUEMFRMKPWUHGXDRIKOOKLDSFIQKWDCPODDNDR AKGGBJKVTCDXUJTKODBBGXEDVVMCXTASQVQUTPPNVMBVLRRBFGKEVYOCGDKEVHWABKGXSXPXNME",
    PersonalInformationPhysicalAndOrElectronicFormat: "electronic",
    InformationPhysicalFormatDescription:
        "MTCBODYSAJRYSJJSRFRQQFCQGQDFXBCOCDKMPAYGKTSUJGMXVWDSMIAGQLTWYSTYGCVOXWCQGLG NQMKRTOFFTRUFWPLHLUXGPKEDCDOFIILOFPVLTSMEBELJLHGAFYIVJQXFHGOQYAWLGGAHTAMSIT HNXJDQXXIVQPQXCSRGKFHPFIVXJNMDULOBVJBAMJMFBBPILGFMJIUKUQHPNFGKKEBEAOBRQRSAS",
    IsPhysicalConvertedToElectronic: true,
    InformationPhysicalConvertedCopyDescription:
        "IHTPLLJRJNPGSAGYUBMHQOENHGCVNHXQLAYADCXCKPOUNNFHWGKKXNBTDFIEINDBPXTRBGURDJV UADUEJHSJEAIYKXUBKQJIMTIMUTPEFSOCYUIKSCFXKMQDFYLFBJDMMLIFTHIPQNDKLGYPOKIHKL DYXKPMGWSHBHOXXOGOJYKAJPPKQWTROGVFDRWEXXWUPXMBOMIHDVADECOHTFUJDASULITFQBPKB",
    PersonalInformationElectronicFormatDescription:
        "HJCENVGNISYFQPMCGXAOSKAIRUGMWSAVYHGXCEMIJHATFFIUIEHQPDAWISLSPSQOSCGJJOACLQE SDRCXOTDWPTCEIXMGOOKTNLHRMQNPMENLGQHBDHCBLVJYWTGCISSYSFFQKJKXGMKLGQXRQLDHLI CHQYCJRNPXNFFKPSBFLAPUMWWWMRYYMLEGVMDKRMQVIGPSTLWKCRLLNGTTCFWYOPKBAXOCOPNXJ",
    IsElectronicConvertedToPhysical: true,
    IsInformationElectronicConvertedCopyDescription:
        "CLRGEUGAXPYOIFLAAWIVJFSUSJYQBTUKAGJPAGNCPJJXOWNSILOMBSAVSWNTVOYDUNNBUVYTJFF XCJKQFRYDYAADLHCMYCGWMLSNWCQHLMHPYMPMQYYXJVFHWQPYPRBHJKKQQVSDBRQMRJEXQOUACI ERHLFYMLRMMEVLJSFGNKEOVWEQSATWADXIEMSVMESXDRHQSNQFVJLFBOUKHOGLQULJFMHVYITIQ",
    IsThereCollectNotIntended: true,
    DoesHavePoliciesProcedures: true,
    HavePoliciesProceduresDescription:
        "HJXVBYYAAERMWCTQXGDXEKAYHCTWDXSJQVYNPPHYSOJAJSWVTKCBFWHWIYOYFBVCKIUADGBIYDE LVBBSRLMIUOQLGBVMQNXPANWPKCOUDTWPLPCMMKOENMRXWREOCQSJLLKIDLHPVREARAAQXIAFYT DTEJAGPBIVNQRSSIKRGTCUTYGNSPFQKAQRLPDJLUKQDXKCVEWHHWDCLIAFCMNYVQLNYYHCEBFKJ",
    IsDirectlyFromIndividual: true,
    WhereWhomInfoCollected: ["indirectly"],
    WhereWhomInfoCollectedOtherDetails:
        "LYBTVDBNRINDAYIBISKDFEQNYHUCOYIEUJITQFVLUYUJQODOEIUOMKRHHMUOHXXSAJIPPOJDWXI RFRPGTRTCTXCKIBRDMWRLLSXCLTMLAFTVUPTQBXMLBDVWLIERLAMCOSGMSNTAFHBNDFOSHBCOKF QCUYFHJUXNHXRSSTRCIENQYNOCCPDEYIYPHNFNIOUDJYTJOLYLLQOCUYDHKCESQTNXXCLFODSSI",
    IsOriginalPurposeConsistent: true,
    OriginalPurposeIsConsistentSummary:
        "QNWWVIMFNUDXKKCDAXQNUGTDVICXLYTWBOXUSWUUROPIJQGNYOMVLKRKTSBMFOTOAGWUMHKCCVU ENBIGNWOXOJXRFHAPSWMQOFBOXBRXCRFEAQBDUJCCIWCAMCYAPKAKELPIYSHLFQUWDTROGWTIUK HJNYSPYFKNMDAWDQDKRGNUXGIADLDLDUDGOYVOYJFRMGMLAQIMOWOKOMKHQRLMBXJQYSIDUOKIB",
    OriginalPurposeIsNotConsistentJustification:
        "DHBEYNFOQUYUDRGAFUWLKIUJAFBYGDMAWYWUMRYECDGBATHISHLKWXUTMRDSMFHNHXXDUKNMVSI VQILFHXYBWROYLOMKXVKJUYMYJMSPTGUJGFNEHHIPECYHLUTLPGTQIRARUMUUFIHQWESFBICPNU KORSBEKIORHLLWLSMEOKUSJWHFPQEIUNRDRCSRTXPVIWYXMEJRDAYKBRFTLVOTEGWSTHFIYTKQT",
    WhyCollectInfoOtherSource:
        "SSJJYWXFFKGUGMCDRHGAKVBTMTQPGQJWMTFIANAYKDECSAOMOSNYHMJVROWFFIXOAJIMHSCEHGP YIFTDVJONWKECSGDRVAUIXWERYJDLEMYJSGADCPQBIUBNRBTCFLALNIBLABELGDJJKUILGAOGJT UTOUKAWCXQBSERWSPJDKKSMUQKVRKXRWSPONIYMVGEKAQPNVOFMUXSPBGSEAEERAYEYNCIKQWGE",
    FormalInformationSharingAgreement: "yes_not_established",
    ThirdPartyCollectionDescription:
        "YOVUCEQTWIPPIEAFBIIGRLKGOLOMJBTEOVIJUOKJIBICILAYFNMDUSNMDPGQPEJVOLAMVQJMXYX YUQSCESFDTVQHKIGLRNGQMBJODRCDDTLQQQKQNKXGWPBIKTJNKCCKTLMSGEYLPBYYJAPSXPXHOY QVDKXDLGFRQQCJAFHKGCGANXKDVQUCEVWRMHSUTHGNWJPTMYAJYBMOWPIEAUGULDNUTKWSLMPYU",
    DocumentationRelevantISA: "upload",
    DocumentationISAMissingExplanation:
        "SKFXUKRVUMPGGOOPTEPUUQNKTXVEIJSDJSBLTMPQTLRBRPQXLJFMXHHCWUDWONNLTMVNMDVHNXA MKHGIBESOSPACHXCAERRWJYESEAXGQCVMEAKBJNUBTXASGAARFXBLKWDKDNDAGMXPTNWGMAQPWQ OPDNLINVSOOIUNKLRSBDMLPQQXSRBHHILCPQIUIHPYHSNRDMDDVDPHQDALVNOVTKHFWSXTCWJSM",
    ISAFiles: [],
    HasExistingPIB: true,
    ExistingPIBDetails:
        "VSBXSWYYOLOSMAUBKTWDWCCSQJJTLOPGMXLHNKUPWWIJLBQTGVDGRKETPIHIMFMYUHGOONMYXHF FPTBQKCJFCHWKODXEQOFXOXMDULCCPPCFHTVNXCXQFUSRXPXAJPCQVIPRHWVYYGPLFRDTHJGNPN FWUEYNNWDWVOPCQWJJREWLCJBGJBSDQCWCVPSCSJJJKKQXYSNEQBSKDTTLCREMEYFTRMGBDGQHU",
    NoPIBStatusReason: "new_pib",
    HasNewPIBWorkBegun: true,
    PIBStatusExplanationType: "text_field",
    PIBStatusExplanationText:
        "NIIPRTLAGNDOYVTRLYRCXTBFDLAVWQBTMWFVFUCIIWAWYBDSVJTEJCFTGDMGSPDOMICCQXLQVIT YINVLWGNHBRWVKTWLMDAIVJPRIFAVYUDMKMWOYSYKXPLCQYAKCXTVFOCXXECQGRHGNKKXWILSEP MKUTWIOUJSSGKUOIGTDAMUYKGBBQKHVLTEIFQTHLAOTWVUONHXOPXCNQKKMVHXKBWGMFLIQLMQA",
    PIBFiles: [],
    NoBeganPIBStatusExplanationText:
        "OMBLMIETEDMGMAMMSRLUDODLWEVHGLDNKRITHXEYUYSDPWDOPAIDEPCAJOOILVMRAXUTRREUNLY GEFQUHBPXJQJOJUEWTVTTKJXQSOGBNWKTOCBGIMYLPHRPHRITOIMFLDVUGYCRUNJLGPYHTWOHWI AWTXAKLHUBKFEDTNVMNUOIWYFTWSAUJPXYLABTSAHOPTVXCXXPCNTGHQYTRGNRGAQUHERSLCTMM",
    WhyNoPlanToReflectNewConsistentPIB:
        "KFKFXCOENCQTYDOWENCRRMGSWLRIHVVVCEEHWDQOAEPHNTYTTFAPSFSWYQHMJFWRFTQUXHABVNR HCTKMYOHNRADJWEHHCSDNSHWIAVXROGWAQTEBOCYJWCTKROHABHNMBHNUWBLCQOXLDDRCAGSYSS APIMRSAGQXQFHCQTBKNJKIQUKLBCOXRNRCRDNLHROBIHDIAUTLNBPEBQXMBGQWQSFDMFKMGPCVU",
    WhyNoPIBExplanation:
        "JYSTCTDJAJDHLNVGNNJAIXJLVJSEUDHNFIVICXLPYUHBMDJCFVFCUWSKOHWRBYOVCOBDQMDPBTB AYOTMWWITDFLRYYOLRNXKDTUNUKJWELTXCEXEWKADJNADXWRTQHAIXTWFTGQMMLPQKMPTBJNGNU BQKHNQXIXDPLQPYYXFQIXOKOJUMGTDDUCAPJKLTNETKTOAQULAVFSRULGVXREROTYTIQAPNLKDE",
    InstitutionNotifyIndividuals: "yes_already_in_place",
    HasPrivacyNoticeStatement: true,
    HasDraftFinalVersionPNSAvailable: true,
    InstitutionNotifyIndividualsDescription:
        "KWYIIMNSLFACEMNETMXWVRKLSYSBEYGGWAPMJNOFRTTLSLHKOUKDGUORLNPITMOMYTFEWATFXRE XFIPBCWYODMHIXFCJURRXGDKQEWLJQDFGVMGTUIVRUJUTOURQPYNMJPQBWYVELPWYGBMLYHNMUY CDEUXUFBNFBLSQJMXQPTRCOUVKAGMGYVYFJUAMDHOQBQGMIIKCXQNWAANIYMTYOGGEMMHOLLNHF",
    NotificationTime: "before",
    HasLibraryArchiveCanadaApproved: true,
    RecordDispositionAuthorityIdentification:
        "PNVLPUWTTCPGWPTGEVOFPRUQROKWXBHOCWXRKTNDHLIEMJBOQTQDNPFXSESAKYVRTAEAQCUJILW UCNYJBGXCABYIJVSFCCPRMSOROBRLQNDWFFTJOLFAAKUHYTKUNGWUMHIJXGUANMLMXCDDBIQQVP VLMERETTDRXNCQQLKRALWXLMPYFKVOGRTLNLTLQGIEXDVDWEKGBOECBXYAORYIWOKGTPDEQYATC",
    HowLongRetainPersonalInformationInPhysicalFormat:
        "FKHWIKGWIIEYDKOJMNOLCNMOSWIMAWMJMQHDTOILQVSAMJDKXEFOHVORXSDKCTVLVTLLCLPXFDU MPLGCWSAKTRYMYWBQRDSVEBRWQSTXIEONDVNBXRXGJLMEOVUTOSCCKMIOSILEYCBPCLICJYSAEM UNORFTXFRUEBMRONWVTCSECQAYVWDAXSWJEWIGPCVMCLEBCXVCAGGFEPLWRFWACRWLDCNQFPGQG",
    HowLongRetainPersonalInformationInElectronicFormat:
        "VMUCGEKFTDKJQGDTKELWMPRKVTEFKSFKROIYKCLCVEWEDGCUXGWCHKTGTJFMAEUBWARBWDJISIA ABANWPDEWOQUQNGWANMLLHWUUHDRBLMWAGQCTFNPDNBDOXMCCLCSKHRREFRPMLDKBSTJVDDUAVH SOPGWMWRESDOGIPIMRNNVGUGWOIKJHGUPFCSVCHAGVANEHFCDJTVXQLLTJIIDLIWMIYBGWMJJNH",
    ControlsProceduresImplementation: "yes_in_place",
    ControlsProceduresImplementationDescription:
        "RGMJPFDFSJGBALCTILMONMNSOTYICOVMKGFKLMFSPMQYCKAPACCKNMTESSTVFUCDMTQSGQHUGTX HYTKTMXQONFTMQGXOXVYJFEIHDXPSKHCMOMRUXLLHJYMTEBDWJULCHYBULCPNIXDFDGWEOCQMKQ RBQXXFMMMLCEAOPNJHKPTOBMYFVJXMINCRCDGDKOVWMQWILQTBXRTUTCAEYSJDOYDNBHLLHGWUS",
    WillRetainInformationUnintentionally: true,
    WillRetainInformationUnintentionallyDescription:
        "YEAHKGVPLMNSFVDDBCMFCKSCNAHQBKWNWCEQDQCLPLCXVKVBHFPELBNNKXSKYENAPYUDQMYJAAO FDQAMUBHYEIYKRJVPCWUJVPPSSIDGYTCGRKXXHNBPJVREIRWHMTEYQUJMAGTLWAYKFRRHLXHNVF HUMRYMLXIAKJLSLHENJEGKJAWAMILCFMDQMLYUBBONMOYBMBGILEYOGVLMTYACLFTWFUGAIJLIO",
    MechanismToCorrectPersonalInformation: "yes_not_established",
    NoMechanismToCorrectPersonalInformationExplanation:
        "IBLGSIJAQHNUJUMIASWRMQDVEAYNPMUVXCCXXJPSGEALXGGRHMBOQOKRWOCSIUKDMQVGSNKPDEL BVSQLGPCCSBQTXITNWGOAUNQIEVDVONCXUSVIYNJHLABHOJCCOBVIRFGHCIHKMGNFXSYFMLOIWG ISAXGSNEGINAIIQSUAKSRJUALRXAKWVAKTEIVHAQOGOKCSBGOPHMOILYWYMNUNTIMMOODHWNATD",
    MechanismToCorrectPersonalInformationDescription:
        "AXBNXNQPVBNTDVCBNFCXBCUCTSOCWJHSGNMMWSMHGWLDOJAQYUIJDEUWDXTEYOSMSTNOJODTRUQ WFGPKLFEPOWNMYPPLJKWVEYAHYYCPVCOENFUMSPXQXEMGKDHTIFFJLBSFGILLDNTMHIYSUCRTLG KQJAEAKJJPDBRVHPRTJNQIDUXNROTXESVTKBYDPWOGRPUVTYTIUDDSGBMNBQHVOLLJFXKFPODLX",
    WillProvideOpportunityToAddStatement: "yes_in_place",
    NotProvideOpportunityToAddStatementExplanation:
        "FMNYDOFFJFIBLGRLEHBPRUFXAWWLFKPLAXLDHTSUJYKMCRHYRKPYBEMJGPYFRSYYPWAMUNDJNFG QNLLOCUSTLAVQFITGLGYERSVTMSAFJQIUXJEMMYJHLHDLNNNURGYMDBXTPRCIUNKTRBRUEGSMVQ IJWPFXKUVGTUMDEYJTPNEJAUKPTYDAQBQMCTSAHRVYEHSDYIDVQSPIAYJBFPDLRVORDYAJGJMXR",
    IsCollectInformationAuthoritativeSources: "yes_but_not_in_all_collection",
    CollectInformationAuthoritativeSourcesExplanation:
        "HALRPAKJGVIRBFAGFDGBDHDKSUIBOAEMCQMQISHRPMOVYNEPRONOIIHAWBXTRITFQVOKRIWMUOL UBCJHYPNFRQBTPADAIGQQMQRYBWCLURWYTYNVJSJUVTWWDKJJJNXTLXHKKKFBNCJYSBAQMGPPWU BIADRLBNINWPRMBLWQIFUTCYSMAURMQITRBRKIKJOKBWVYRXATEBHXXGGAJFKGVUWNUALIBNGYQ",
    ProgramAccuracyDescription:
        "HASELNEEYWKEJURAMIRHTYUTTMBDKBECNHEXHWOWVRRLVLNSFUKFONLIEYKXMASXRIPBPTSOTTL FHSGSBFFEPVISIBYPCDQPFAVNAQCCDMXSVWPJROYOBIIEYDPVGIERWVAHVSRKDCBDWOVLKPWNDC LVLYUNAAGMPRVNIUDLJIYHVWSUMXPECPIDTLQSPOAVKHDFAHNAARNHBDANGYABKCKAJSSWEJUTH",
    ProcessDisposalPhysicalFormat: "yes_in_place",
    ProcessDisposalDocumentationPhysicalFormat: "yes_in_place",
    DisposalPhysicalFormatDescription:
        "XLJFXSXAKJMYKGPCUVGEAYCCMEGFXPVARMOEMAHFWVEUTSVDQHTIQKWXJGSTLRCTMMGXRKOTNBG DOPOOBLMHIFWUBXIXSGVITKOFCKRAGGNHQUJBXNGBVBYRTALQFDXWAIJEAIMQSLBCQPDGOGYEAT TNQXUKOLUASCCIVQQGGRXLANWIFSMJBQGRYCEGTIOFQQRGPJFAKTWDWINCAMEVXKYBUJJTMJMWC",
    ProcessDisposalElectronicFormat: "yes_not_established",
    ProcessDisposalDocumentationElectronicFormat: "yes_in_place",
    DisposalElectronicFormatDescription:
        "HHTMTGXBGUDWLXFPODQQMCGQTJQHTCUCRKHKOCYIEETGYSXXQTPCJUOEACSJOQGEABEAQTBMDHL FKIYDICIRWUGXMEVGCYNSYNRLREMFIVALIQBLPNWSLJKIUURSKYIWGWGVPMLEPCJBTTOVCKQNCU LYBATVEDPKIYOPOMSKARFOLLSPYYFGJJRVNXGQBSJMXTEUWAPPFYLQHVNPHEWEXJAYHRBPGBIHI",
    TriggerProcessToDispose:
        "LSRJNKHJUAQEPDMESBHLAVRAAFQQRIEUYWPPLATUVKCPJDIPWIHXUFEOBQJHTQQLUUERMVRRGLO SXSOXANBXLCUMRWKODNLYJCORKVANFEGUBXFGAYLPGFONHVQGVVTAGNJUDVMDNNRHUAKSQDOEBV BJLCXBKEDSVMXAAGNCUBKPOIDSEKEMNLWJGTHRGCEVXWEUWPEQACKVMKTCYEWYYQEKONTGXUUSV",
    WillKeepRecordOfDisposal: true,
    EquipementDeviceDeleteStoredInformation: "yes_in_place",
    PopulationImpactedByUseOfPI: "all_employees",
    PopulationImpactedByUseOfPIAdditionalInfo:
        "MQRETRKUOJMOUIMRPRYLMAAOEIXPVDDTGJTRMABLCXALMSMGIXUSKPSMQCYKTUYLGSHLOUFOPMJ CIIWGFDUKEGXXYCVYONHBSNXCEBLBAFWKBXREJVOEAPEXMJWWMTXEACIUJUCERSJYJMVBJRPSXC UQHPTSCEUFTSLEAVPSRMDWHPGLREDNPUGWEHMNHLXIWGRYIFLNSHFTIWJQJHBWBGOXMNYRIBLFN",
    DoesFocusVulnerableGroups: true,
    FocusVulnerableGroupsDescription:
        "OEJNTJFILQRCELVIRXCLSHOUANYABETNPAJELGDLWBLAJUSBRGHKTDPHONMGJEGHVEMEBRVLUQN MFXLVPOIGDUXAURTAPVITOSVCGAXPKHHWLUFFOLOLCONBNPOYSAWOBSWMCIPPQSUUMBOYLOKDGV VNCNKWCFJLAEUNJGMCTMMJKUNVEBBEOTMGLVBRJQPNRMNBHSCLOPGWRMCHANSADFVFRNCMETSCV",
    SizePopulationImpacted: "small",
    HowInstitutionUsePersonalInformation: "administration",
    HowInstitutionUsePersonalInformationMoreDetails:
        "HIRPMJYIDWEDYBYFXICHGNUBULMPRGQOMVLROMREIASJVEUECGPFKTLTMQTAWIQWGOQCPGQLPWY RSMLKJYCXJDJHOVXEGEDFNGQLNJSINBKURMTLDXOTOKTHMEWJYYHWEHELVAVAGTJISOPCCLAIPI NWTISJUROPXOMGNIGFNBMHHWURXLGBRRAECDOTAMLPGQPVQSBCWUFTPGPVMBLJLNWGOHDKSLEAP",
    InstitutionUsePersonalInformation: ["purpose_collected"],
    PersonalInformationUsedFor: ["profiling_prediction"],
    DoesUseDeIndentification: true,
    UseDeIndentificationDescription:
        "LVIKMDPGOAOPFUFQQJWRDVSLTYSHAMMVFOUELVNVBTONMERXNCYWRKOOCWQNKIFCMSJPYAFTVAP QJHKUCEPXITACEOGIIXFAPEOQBJBMNSJWLTYACWPXRJWEXDEXGRPTQRAFRTTRDDKOKCQKPGGLIH YFFWXFAMUPTNEXDQYLNNEQIPDSSHFFSUBJDWMNXUJCVPPREWORNYGPKHVPSEMRHOWXLTUGELMRD",
    IsCollectionReasonOtherThanStorage: true,
    DisclosePersonalInformationMethod: ["legal_authority"],
    WillAllPICollectedBeDisclosed: true,
    InformationSharingAgreementInPlace: "yes_not_established",
    DoesISARequireUpdates: true,
    ISARequireUpdatesDescription:
        "YAYMJGJXFGTXTMGSDVRPPDFPXXHCWKKJBNXLPTCYITFPQWTUJGHSVYWVUIOKYHBTUJVFNTCJSSG JCCRJQQAYNVCRVTLBIMEUNPGCTGLWVOATQHLANMPGRQJQVHRYOQEIUJVLUOOKEDCXUIANHKMUVX UIIUWHSIXHNICYORKUIGFVGVJAATYMQDFTUCOSGWGBWCUKLPOVJABRYXCMKVHXILQJCHELDRNKA",
    NoISADisclosureDescription:
        "CEWAFIKJWXEVQXUFGQTIBHGXCJDUCNNXSDNAMECTFKKBDCYJSGCNXPNUWXWVEPHIJGDNKUSBOAD HJROYLYQLPKOOIPFGVPIMRLNSUTBATJSUNXFXOKSLEDEEDBNDQFOEYAPXEUDRXPRGQSAKJHQLVV HIOWDLQYTNCFWXPSFLIIKBDJXFRMPEYQYJSPTMEIEQLBDTYTFRBMJWRGFFXXTEIPOKFMFAXRHAD",
    InformIndividuals: "yes_not_established",
    InformIndividualsCommunication:
        "RTAGPOJOQSFCPSEEYKTPRDNBBKBPLIFXHDECOODHLWRQJDOMFXQAXQROGXFFMSDIMGTLOCOJGLE LMAOIVQAOMQJHJVLUBDOJVNLRWVMQIRCVCVVIBVXOLUDNKJELGDYJVKOXOWLADIFTOMFNACTFFY JPRFMQAHWYJSFWLTBHCQYBKHNUSHXPKAAFFMCMKYLFXIUJQBDEQPBQJIEJQRXSIHNJRARXRNWCF",
    FlowChartFiles: [{ content: "3916", name: "css.txt", type: "text/plain" }],
    HasSecurityDesignation: true,
    IsSecurityDesignationSameToAllPICollected: true,
    HighestSecurityDesignation: "confidential",
    SecurityDesignationDescription:
        "NYPHCLHWDIRETJDDMHYIGFXLDIXMNDTEVQSQURVEEEIQLJKGSDYVDCUHBEDSNUJANMHCQMHTLUD FJOYKCOOKANQOBTCLDFLNHCJAAXDGGQQMVDQCECHGLHFLETTOSEXQKDWHEYJEKIEJWERWCYGAWE IYTXVPHAPALUIQHNOJCFNXDNIGMGOXHIFNTEFECFOHMMEMXJUGQPRTTJUGOOCALQRCPTVDHJHVP",
    CompleteSecuritySssessments: ["yes_not_completed"],
    BehalfMultipleInstitutionOthers: [
        {
            BehalfMultipleInstitutionOther: "",
            OtherInstitutionHeadFullname: "VTVTURWGMYCEWPTYAKALBWCKY",
            OtherInstitutionHeadTitle: "NENBAVWYRSDOVHMOMLYWKDCVG",
            OtherInstitutionSection: "LMNBGHIETTQPMDWHVSKQKOCTN",
            OtherInstitutionEmail: "YMMCDGWTMP@gmail.com",
            SeniorOfficialOtherFullname: "KQDFVRVHLMANVUUSQJGDWMGYL",
            SeniorOfficialOtherTitle: "LWNIBANHXSIVIYIFLLYPQLGAD",
            SeniorOfficialOtherSection: "HDCAOEUGVIWYRLXPMIGDHTJCX",
            SeniorOfficialOtherEmail: "OODIBTLLHS@gmail.com"
        }
    ],
    DocumentationRelevantISALinks: [
        {
            Link: "http://IXKDQWVCFR.com"
        }
    ],
    OtherPartiesSharePersonalInformation: [
        {
            Party: "ERVQJFKUIFIYCXAKOLSAWBDYM",
            PurposeOfDisclosure:
                "XKQEGPQEFRCXGOHJGBJXGARRTDFYTKMKNNMSPVBUPHNHYEHCHCYRHVMXSYJDJRKUEQKRBOSJYOH JLBQMWSHSWJCAPTVXOWQUREDSNGUFBTFREWPQVEJBPQCIMCXAAYRPOKQGXWXPWCRDEKVRDFBKMO FWSRJILDDRDQXRQMDKNDJQWEYVUGWYDGROJGIYBBJCHDNKXNLOJWQCBNAORMMEFDNVXIHJDDILS"
        },
        {
            Party: "green party",
            PurposeOfDisclosure:
                "XKQEGPQEFRCXGOHJGBJXGARRTDFYTKMKNNMSPVBUPHNHYEHCHCYRHVMXSYJDJRKUEQKRBOSJYOH FWSRJILDDRDQXRQMDKNDJQWEYVUGWYDGROJGIYBBJCHDNKXNLOJWQCBNAORMMEFDNVXIHJDDILS"
        }
    ],
    PartiesSharePersonalInformation: [
        {
            Party: "other",
            Description:
                "HVUCMUUDSVHSKUNPTSRQNEJDMERDHVHCVVNVLWYGHLCUCQAYYJRKSCJCMQPICRVVNFVOGREWSLJ FOPRBEBBTBVXADKVPXEMWTCVHKEJNCUAWLAUTMLVMCFKLWBNECCRUNBLMSJQARNQFVANCOBCMHA BMWFJTIIBNUGYMCKWXMEHIYBFXRLATMKDYPDHLDACPCCDFVSBAOSVGUSMVYKBVHGAJDAWYCLTLC",
            RelevantISASourceType: "link",
            ISAFilesParties: [],
            RelevantISALinks: [],
            DocumentationISAMissingExplanation:
                "TEFDTIXQXSJATYSNGFTTPIJSWIUAUEHMCUXBRHLBITUNKRMGXPCBFITLTLGLNXVSLWWXBRUXSRK LJEWRYLQNWIJUTVRDDTFCQAEPQAKYAFVCNQSYMOLCBTGSKWGFMTEHYFTIYHBXBRMRLGGCDSQNHD LDDAMXWPUEWCLFYCDSQMLCWKTDWVTVKKBOGKTPHYGJBSYTKCFSXGOOKIGRGJABVYSMAVXOINLRF"
        }
    ],
    PersonalInformationCategory: [
        {
            Category: "from_social_media",
            SupplementaryInformation:
                "MTKWMIBPWVEUYDLQPSOGJWBLBWFBPHAPWNQFGETUFOPGQEQVXBYCPMGPRXVPCYAPUNXLLGKKXTB FDMHUUHQYXYAERJEHGAMORDHYTXJAKUPONCLTLLCHJOLLARWJBDNLIUNAEHBWXPNCJKQOWKUUXF JWJOTUVYYLKTJRRXPRWDCAHDAGKQLRIHOFPBJJBWQSBGVQOMHWOSQWXIOGNNJEMGCDEEBPOFQAL",
            PersonalInformationElement:
                "NGRSLODFORWHANMPWESBWHFVSIVASEGUVGHWPJQFNWADOEJNWATOHWGFAVYCRDLJKCKSGOYMNNN DVVMGPJPUFPHDPMUNAHFXJVJNMHGWXCDXDFTSAVRNUAPWLGBTKUINNLTALYSICRWDMIYKSBMEPQ UIKRBULEECWXLQQWJELGKDJKGUOWLSEWLCTVVHECESMXFEWCBRPSILDQYALGGNSLXAMIWTACYIB",
            PurposeOfDisclosure:
                "EOPNAKNSXLLGCSTAJYBOKFWKFQNGPCSMDNNIRHPDRQCQSWKWBRGHQEHXREHJWGCVSYDOELHBIXV MDVWPMNVYVSKUDTDIBTHTDVPJPMTQEBVWEIUSEFYQNMYHOTJMIABWEVIHFNYYSFTUWMPUXJDUTQ FERBEUHYMPWEJABVPDQAMCDHDAIHQJPFPVAVKJEFAVFVSCRNXLFCVGIDAKWELAIDARONAFLGXLY",
            ReceivingParties: ""
        }
    ],
    PNSStatement: [
        {
            Description:
                "XSSXCIKDXVTFTBFUNUDETEDJEXIVGEOUCPYRJYHFJAVKIDBUKBPXDMASPITDYOWTHYCDCMKNNWU YEAAUMEHMTUXABWRIRTLHQRKXFNUSWKMKOXOWGCTLIFNDBIETLCDPISIMPCOXINPIIMKDIUCPYY TRRWBTNNWTYLTQYEGSELYEHMNGQBNAGQXVFATLIGEDLJTVNGWXUUOAJOKEIUDLYWNHMXLXJUJXH"
        }
    ]
};
