export const testData = {
    AnotherContactEmail: "anothercontact@gmail.com",
    AnotherContactFullname: "Another full name",
    AnotherContactSection: "Another section",
    AnotherContactTitle: "Another title",
    AnticipatedEndDate: "kjhkjjhkhj",
    AnticipatedStartDate: "fasdfasdfasdf",
    AwarenessActivities: "yerryryytr",
    BehalfMultipleInstitutionLead: "1",
    BehalfMultipleInstitutionOthers: [
        {
            "OtherInstitutionHeadFullname": "Hugo Roule",
            "OtherInstitutionEmail": "yougo@hotmail.com",
            "OtherInstitutionHeadTitle": "Rouleur",
            "BehalfMultipleInstitutionOther": "2",
            "OtherInstitutionSection": "Astana",
            "SeniorOfficialOtherFullname": "Julian Alapolak",
            "SeniorOfficialOtherTitle": "Puncheur",
            "SeniorOfficialOtherSection": "QuickStep",
            "SeniorOfficialOtherEmail": "juju@hotmail.com"
        },
        {
            "OtherInstitutionHeadTitle": "leader",
            "OtherInstitutionSection": "Astana",
            "BehalfMultipleInstitutionOther": "Mental Institution",
            "OtherInstitutionHeadFullname": "Lopez A",
            "OtherInstitutionEmail": "lopez@gmail.com",
            "SeniorOfficialOtherFullname": "Tadej Pogachar",
            "SeniorOfficialOtherTitle": "Sprinteur",
            "SeniorOfficialOtherSection": "UAE",
            "SeniorOfficialOtherEmail": "tadeg@mymail.ca"
        }
    ],
    BehalfSingleInstitution: "2",
    BehalfSingleInstitutionOther: "Another institution",
    ChangesToBusinessRequirements: "fsdafsdf",
    ContactATIPQ16: "conduct_pia",
    ContactATIPQ18: "conduct_pia",
    ContactATIPQ110: "conduct_pia",
    DetailsPreviousSubmission: "this is a bunch of details about the previous submission",
    DoesRequireModificationToIT: true,
    DurationOptions: "pilot",
    HasLeadInstitutionConsultedOther: "yes",
    HasLegalAuthority: true,
    HaschangesToBusinessRequirements: true,
    HeadYourInstitutionEmail: "jack@gmail.com",
    HeadYourInstitutionFullname: "Jack Travis",
    HeadYourInstitutionSection: "My section",
    HeadYourInstitutionTitle: "Boss",
    InvolveNewSoftwareDescription: "rewrwerqwer",
    IsAnticipatedEndDate: true,
    IsAnticipatedStartDate: true,
    IsInvolveNewSoftware: true,
    IsNewprogram: false,
    IsProgamContractedOut: false,
    IsProgramInvolvePersonalInformation: true,
    IsProgramRolledOutPhases: true,
    IsTreasuryBoardApproval: true,
    LeadInstitutionConsultedOther: "yes",
    NewOrUpdatedPIA: "new_pia",
    NewPIAAllReferenceNumbersAssigned: "V13R5t9O",
    NewPIANumberAssigned: "new_pia_existing_reference_number",
    NotInScopePia: "';lk'lk'kl;'kl;",
    OtherInitiatives: true,
    OtherInitiativesDescription: "gsdfgfg",
    Overview: "yereryery hfdhfg",
    ParticipationOptions: "participation_mandatory_and_automatic",
    PersonContact: "adam yates",
    PersonalInfoUsedFor: "non_admin_purpose",
    ProgamHasMajorChanges: true,
    ProgramName: "ze programme",
    ProgramOverview: "utyurturturtyu",
    RelatedPIADescription: "related descriptiohjfj",
    RelatedPIANameInstitution: "related instituion",
    RelatedPIANameProgram: "related program namexxxxx",
    RelevantLegislationPolicies: "jgfjg",
    RequireModificationToITDescription: "fasdfasdfa",
    ScopeOtherPhases: "lkjl;jkjkl",
    ScopeThisPhase: "gfhfghh",
    SeniorOfficialEmail: "adam@yates.com",
    SeniorOfficialFullname: "adam yates",
    SeniorOfficialSection: "michelton",
    SeniorOfficialTitle: "rider",
    SingleOrMultiInstitutionPIA: "multi",
    SubjectOfPIA: "other",
    UpdatePIAAllReferenceNumbersAssigned: "A3Rt67U8",
    UpdatePIANumberAssigned: "update_pia_existing_reference_number",
    UserEmailAddress: "test@gmail.com",
    WillITLegacySystemRetained: true
};
