export const paTestData = {
    "FilingComplaintOnOwnBehalf": "yourself",
    "RaisedPrivacyToAtipCoordinator": "yes",
    "WhichFederalGovernementInstitutionComplaintAgainst": "3",
    "NatureOfComplaint": [
        "NatureOfComplaintOther",
        "NatureOfComplaintDelay",
        "NatureOfComplaintExtensionOfTime",
        "NatureOfComplaintCollection"
    ],
    "IsEmployeeChoice": "general_public",
    "AdditionalComments": "iuyiuyuiyiuy",
    "Complainant_HaveYouSubmittedBeforeChoice": "no",
    "Complainant_FormOfAddress": "Mr.",
    "Complainant_FirstName": "jf",
    "Complainant_LastName": "brouillette",
    "Complainant_Email": "jf@hotmail.com",
    "Complainant_MailingAddress": "66",
    "Complainant_City": "gat",
    "Complainant_PostalCode": "J9A2V5",
    "Complainant_DayTimeNumber": "6135656667",
    "NeedsDisabilityAccommodationChoice": "yes",
    "DisabilityAccommodation": "iuyuiyiuyiuy",
    "Complainant_Country": "CA",
    "Complainant_ProvinceOrState": "2",
    "Reprensentative_FormOfAddress": "Mr.",
    "Reprensentative_FirstName": "jf",
    "Reprensentative_LastName": "brouillette",
    "Reprensentative_Email": "jf@hotmail.com",
    "Reprensentative_MailingAddress": "66",
    "Reprensentative_City": "gat",
    "Reprensentative_PostalCode": "J9A2V5",
    "Reprensentative_DayTimeNumber": "6135656667",
    "Documentation_type": "none",
    "WhatWouldResolveYourComplaint": "gsdgdfgsdf",
    "SummarizeAttemptsToResolvePrivacyMatter": "gdfghjvbcvbcxvbxcvbxbcvb",
    "DateSentRequests": "qwerewr",
    "WordingOfRequest": "hgdffgh",
    "MoreDetailsOfRequest": "oiuyoiuo",
    "DateOfFinalAnswer": "gfhfjgj",
    "DidNoRecordExistChoice": "yes",
    "InstitutionAgreedRequestOnInformalBasis": "not_sure",
    "SummarizeYourConcernsAndAnyStepsTaken": "poiuiop"
};
