export const pbr_test_data = {
    OrganizationName: "DFLSATJOYNFMWTAFPCNVMXOCI",
    OrganizationCity: "ATJNCFJXANGVUHGXWSXKGSJNH",
    OrganizationStreet: "YWRQFNDVDQFCKUMBIQFCXSQXB",
    OrganizationProvince: "1",
    OrganizationPostalCode: "A1A1A1",
    RepresentativeType: "internal_representative",
    ContactName: "XIXACAVXWSNOMOVAIDMGEOQNO",
    ContactTitle: "QJAEGLRQVAIIMIGRUKLFUYARG",
    ContactPhoneWithCountryCode: "+1613-436-2326",
    ContactPhoneExtension: "",
    ContactEmail: "BTRUVAVXIQ@gmail.com",
    ContactStreetAdress: "RNSAJVLRPDOJDTUPLQLEMBNDS",
    ContactCity: "CDYFJNGEVCKXHDDGFGILLUJCC",
    ContactCountry: "1",
    ContactProvince: "1",
    ContactOtherProvince: "TBMSGXIIFBWVWEQMKYMBPUBKW",
    ContactPostalCode: "A1A1A1",
    NumberOfInvidualAffected: "587",
    NumberOfCanadiansAffected: "228",
    NumberAffectedComment:
        "LAVRGXYXSEQEFPDQERTRKYXOHJLRBXVXDXVKDBUQHBXUUNEHACLSRDDLBGJWMHWUISBHTSNCVDJIBDTSEDQXLCGATKJVQXDYEDLCMWNH OIVNSTKWMQRIPXILBMIIRLXYJEWRQGHPJJDFRGAALIAFTJFUFPLJEXWWXOJPMFVKJSGOFATUMIWILREAXCMAUXKKMFHDWJMGLOVBCQOEVPVUBNLFJIQJSVPLHUCYSQXDUPVVVDWHMHEEBPJXT",
    DateBreachOccurrenceStart: "2020-11-03",
    DateBreachOccurrenceEnd: "2020-11-03",
    BreachOccurrenceComment:
        "CXOXUOEBFHSGTPBEXUNJBWSYDBPKWVQENLBJMUHNTYTPTSLPYTAQIBPEEPUTXSDJQOSHORRDMYOBCDEJPAKDUYULUVEVANOAUKYFYD AGBWEIMOCBKKDXHANQSHMRNVCYKFQEYJLYEBXUMYGTDKOJQRUWHLRQISFTFXWIKWLAQXDYOVGIFXKKMOSVKTVMRUQKUEPNBWIFXOSSOUIKFJKJIUGPEBWPAYIVGRDJGRHHOELXVAHOLLHIJHCAX",
    TypeOfBreach: "loss_physical_devices",
    BreachCircumstanceDescription:
        "XIATQEQWCGUIVEIPITSPDJREXKXLILIKTNXFJCUXNBVPTAOFHHYRCHXOPUVFFENPXJNHFCFGX UBBNCKXUSEBMPIMPJPNFPRINFQJLHYEBRTHFVANJXJMALDIBBQUMRAICSNHKBLNSYAUVAGSJCDHFEIBCIHKPERIRLFMIRCILVTAKILBTXLKNRCWKMFCSBWOHQCJUSKQYUVJKHPTVGPRSHUYIHCVMAOKXFSTFCGBNTKRVSMCVLFMKFVAUD",
    SecuritySafeguardsDescription:
        "ROBXDNGHDGAPFLRVFMFWCMNKREIWVRGIAQQFRSBPTIXGXCYXYNAJTLWEAQFXFJKLAQPOTLDMLOCSOHLPEKWIRVNNSLFBMDKKWMGGMKD NJNXFJEPREPSULCSDDBUIGCAIDRVBBFDTGJYEWIEOVMVVJPXUTCDKPUGGMPBRIOPYMXNCDOGUWFLTFDXNSBHYBRELDRQHGMGHVWJKCVQEUHMJIMBJQNXGHQWTTBXKXXOKXEWHSMKVJCDSFTDPQG",
    SubjectOfBreach:
        "YCRQYGISHJTYRFMSXNVPDRVWBAOWEKNUFQFNPFKARCHHSPRJGFJBOHHHFTPYRLNWUXSAYXDRCVWBJODKIFPXAMGWJWHUPKIFNKLUVQJH BQXSJGXQPEPMUOWHQUQCQICQMQMYCIORUHVIONNDYQEKUVKXNEDAAHQSOGFRSYNGPXQNRNSCHMCYDRVQGNLXFNQMQDTIIUJYCXUVEVGYKARMEQPWJOKFNPBBGDVOTKTMCCWFWALKHLMEUEIYNV",
    IsAffectedNotified: true,
    DateNotificationBegan: "2020-11-03",
    DateNotificationCompleted: "2020-11-03",
    MethodOfNotification: "directly_and_indirectly",
    IndirectlyNotificationDescription:
        "NMWXXDJCMKRSGMIHDUCKTEOKIDEIANEOTJEMJQYAOKSIYGVMKKNLMSNIXLOTXBBYFCXVHUXMUCUILGKBHRWOYRBBVVOWBFBNISCVIYEOMBPKXE VRBNMGDLANBWYLGAKPBGAREOSHMICWBQDRYWVNRTKVSNULYSILPAIQDDMLTETUJCLJSHLJEWXGUDYPSHHSAPGBHLNUJJSMYPMPCLRRGXGSCCVYEWRMWBUSUJBHSQYUEKGFQINHOOMBIN",
    NotificationDescription:
        "BVRCNRMJIGQEFVRMBGGQIYYAOOOYGVSYRQHXXTJTHDDIFMDMOTRKKRHBWRMYCNDLMQMONSNHWMJFUQTBLBJLEIOAJGBGGJQSARUNANYVGJNWIBFGWKMAEQHECMF HQHBMUPFDUFBWCNFTTQQHAUIVWPOIJQKNIQFYIACRVBKQJOXPKNJLUWGUXFPEAVTDUMNLIGKTOXKYJRLHRXWUHYSKKJADKWRAHHVVAMHECPWVMHLGSHMBXXVUTDAYFG",
    StepsReduceRisksDescription:
        "IKWWRVJSNYVKSOOWQMMMGJUFLHQMLBQAGCBQCDNGRKNCJOYQAFGGRPHYPRLKEVHLHVEQMWTMXGUVVRUVIALFUJIPTCBKRDBUCCTNKHDDLSHKULDWVPCEJ BPXMNVKUJUUFASSXHKAVITBBXUHYENBBVKBLUAWLRHBXMETRJXOFBIBHNVORNLQVSSJORHCHMODBRDOSBOPGXVYNJTWYKFWGPFESUEACUHRMEAOKGUQYUKWWSVFWJDVHRVKLX",
    StepsReduceRisksFuture:
        "SXPBBKYGMPMECWYSYNMQPRNQOYXJINIVPRBDAQNMVTHWLFGEGUGLVESBKYMCMOXYHPOJUVRHAAUVJQEISTDNGVALYASADKAGVIOUQWIJCXLUJWQSUEJRLKRKPCJUDRE OANYBBJRULSKHKFCBJYFYBHTLPEFNMNGJTVUUXPRLLNFSYJAKAILEMEMRSNKWDEIXMANNJGDTHTMNBBLFDUMDBCWOJDCJETHHEHFXVMATFRVSQYPQBETIQEVKDX",
    OrganizationDescription: [
        {
            Name: "SOXVDYDKEOGGCLGMRRMTSPLYX",
            DateNotified: "2020-11-03"
        }
    ]
};
