export const pbr_test_data = {
    OrganizationName: "DFLSATJOYNFMWTAFPCNVMXOCI",
    OrganizationCity: "ATJNCFJXANGVUHGXWSXKGSJNH",
    OrganizationStreet: "YWRQFNDVDQFCKUMBIQFCXSQXB",
    OrganizationProvince: "",
    OrganizationPostalCode: "REMTQOMRTUOUVACJYBSDOQFAF",
    RepresentativeType: "internal_representative",
    ContactName: "XIXACAVXWSNOMOVAIDMGEOQNO",
    ContactTitle: "QJAEGLRQVAIIMIGRUKLFUYARG",
    ContactPhoneWithCountryCode: "+1613-436-2326",
    ContactPhoneExtension: "647",
    ContactEmail: "BTRUVAVXIQ@gmail.com",
    ContactStreetAdress: "RNSAJVLRPDOJDTUPLQLEMBNDS",
    ContactCity: "CDYFJNGEVCKXHDDGFGILLUJCC",
    ContactCountry: "",
    ContactProvince: "",
    ContactOtherProvince: "TBMSGXIIFBWVWEQMKYMBPUBKW",
    ContactPostalCode: "SWWALILUYHWPSDJBCJDVHVNLQ",
    NumberOfInvidualAffected: "587",
    NumberOfCanadiansAffected: "228",
    NumberAffectedComment:
        "LAVRGXYXSEQEFPDQERTRKYXOHJLRBXVXDXVKDBUQHBXUUNEHACLSRDDLBGJWMHWUISBHTSNCVDJIBDTSEDQXLCGATKJVQXDYEDLCMWNHOIVNSTKWMQRIPXIGLBMIIRLXYJEWRQGHPJJDFRGAALIAFTJFUFPLJEXWWXOJPMFVKJSGOFATUMIWILREAXCMAUXKKMFHDWJMGLOVBCQOEVPVUBNLFJIQJSVPLHUCYSQXDUPVVVDWHMHEEBPJXT",
    DateBreachOccurrenceStart: "2020-11-03",
    DateBreachOccurrenceEnd: "2020-11-03",
    BreachOccurrenceComment:
        "CXOXUOEBFHSGTPBEXUNJBWSYDBPKWVQENLBJMUHNTYTPTSLPYTAQIBPEEPUTXSDJQOSHORRDMYOBCDEJPAKDUYULUVEVANOAUKYFYDAGBWEIMOCBKKDXHANQSHMRNVCYKOFQEYJLYEBXUMYGTDKOJQRUWHLRQISFTFXWIKWLAQXDYOVGIFXKKMOSVKTVMRUQKUEPNBWIFXOSSOUIKFJKJIUGPEBWPAYIVGRDJGRHHOELXVAHOLLHIJHCAX",
    TypeOfBreach: "loss_physical_devices",
    BreachCircumstanceDescription:
        "XIATQEQWCGUIVEIPITSPDJREXKXLILIKTNXFJCUXNBVPTAOFHHYRCHXOPUVFFENPXJNHFCFGXUBBNCKXUSEBMPIMPJPNFPRINFQJLHYEBRTHFVANJXJMALDIBBQUMRAICSNHKBLNSYAUVAGSJCDHFEIBCIHKPERIRLFMIRCILVTAKILBTXLKNRCWKMFCSBWOHQCJUSKQYUVJKHPTVGPRSHUYIHCVMAOKXFSTFCGBNTKRVSMCVLFMKFVAUD",
    SecuritySafeguardsDescription:
        "ROBXDNGHDGAPFLRVFMFWCMNKREIWVRGIAQQFRSBPTIXGXCYXYNAJTLWEAQFXFJKLAQPOTLDMLOCSOHLPEKWIRVNNSLFBMDKKWMGGMKDNJNXFJEPREPSULCSDDBUIGCAIDRVBBFDTGJYEWIEOVMVVJPXUTCDKPUGGMPBRIOPYMXNCDOGUWFLTFDXNSBHYBRELDRQHGMGHVWJKCVQEUHMJIMBJQNXGHQWTTBXKXXOKXEWHSMKVJCDSFTDPQG",
    SubjectOfBreach:
        "YCRQYGISHJTYRFMSXNVPDRVWBAOWEKNUFQFNPFKARCHHSPRJGFJBOHHHFTPYRLNWUXSAYXDRCVWBJODKIFPXAMGWJWHUPKIFNKLUVQJHBQXSJGXQPEPMUOWHQUQCQICQMQMYCIORUHVIONNDYQEKUVKXNEDAAHQSOGFRSYNGPXQNRNSCHMCYDRVQGNLXFNQMQDTIIUJYCXUVEVGYKARMEQPWJOKFNPBBGDVOTKTMCCWFWALKHLMEUEIYNV",
    IsAffectedNotified: true,
    DateNotificationBegan: "2020-11-03",
    DateNotificationCompleted: "2020-11-03",
    MethodOfNotification: "directly_and_indirectly",
    IndirectlyNotificationDescription:
        "NMWXXDJCMKRSGMIHDUCKTEOKIDEIANEOTJEMJQYAOKSIYGVMKKNLMSNIXLOTXBBYFCXVHUXMUCUILGKBHRWOYRBBVVOWBFBNISCVIYEOMBPKXEVRBNMGDLANBWYLGAKPBGAREOSHMICWBQDRYWVNRTKVSNULYSILPAIQDDMLTETUJCLJSHLJEWXGUDYPSHHSAPGBHLNUJJSMYPMPCLRRGXGSCCVYEWRMWBUSUJBHSQYUEKGFQINHOOMBIN",
    NotificationDescription:
        "BVRCNRMJIGQEFVRMBGGQIYYAOOOYGVSYRQHXXTJTHDDIFMDMOTRKKRHBWRMYCNDLMQMONSNHWMJFUQTBLBJLEIOAJGBGGJQSARUNANYVGJNWIBFGWKMAEQHECMFHQHBMUPFDUFBWCNFTTQQHAUIVWPOIJQKNIQFYIACRVBKQJOXPKNJLUWGUXFPEAVTDUMNLIGKTOXKYJRLHRXWUHYSKKJADKWRAHHVVAMHECPWVMHLGSHMBXXVUTDAYFG",
    StepsReduceRisksDescription:
        "IKWWRVJSNYVKSOOWQMMMGJUFLHQMLBQAGCBQCDNGRKNCJOYQAFGGRPHYPRLKEVHLHVEQMWTMXGUVVRUVIALFUJIPTCBKRDBUCCTNKHDDLSHKULDWVPCEJBPXMNVKUJUUFASSXHKAVITBBXUHYENBBVKBLUAWLRHBXMETRJXOFBIBHNVORNLQVSSJORHCHMODBRDOSBOPGXVYNJTWYKFWGPFESUEACUHRMEAOKGUQYUKWWSVFWJDVHRVKLX",
    StepsReduceRisksFuture:
        "SXPBBKYGMPMECWYSYNMQPRNQOYXJINIVPRBDAQNMVTHWLFGEGUGLVESBKYMCMOXYHPOJUVRHAAUVJQEISTDNGVALYASADKAGVIOUQWIJCXLUJWQSUEJRLKRKPCJUDREOANYBBJRULSKHKFCBJYFYBHTLPEFNMNGJTVUUXPRLLNFSYJAKAILEMEMRSNKWDEIXMANNJGDTHTMNBBLFDUMDBCWOJDCJETHHEHFXVMATFRVSQYPQBETIQEVKDX",
    OrganizationDescription: [
        {
            Name: "SOXVDYDKEOGGCLGMRRMTSPLYX",
            DateNotified: "2020-11-03"
        }
    ]
};
